import * as THREE from 'three';
import {sha256Hex,lengthUtf8,concat} from '../observer/vfx/shared/sha256';
export type PaletteRole='Background'|'Environment'|'Entity'|'Positive Relationship'|'Weak Relationship'|'Repulsion'|'Cluster'|'Context'|'Condensed Entity'|'Event'|'Selection'|'Glow'|'Particle'|'Vortex'|'Accent';
export interface Palette {readonly id:string;readonly name:string;readonly colors:readonly string[];readonly roles?:Readonly<Partial<Record<PaletteRole,readonly number[]>>>;readonly builtIn:boolean;readonly metadata?:{readonly createdAt?:string;readonly updatedAt?:string}}
export const builtInPalettes:readonly Palette[]=[
 {id:'hru-default',name:'HRU Default',builtIn:true,colors:['#52d8ff','#ff4f9b','#58cbe8','#ffd37a','#8effc1'],roles:{'Positive Relationship':[0],'Repulsion':[1],Glow:[0,2],Event:[3]}},
 {id:'high-visibility',name:'High Visibility',builtIn:true,colors:['#ffffff','#35e7ff','#ff4fbd','#ffe36e','#8effc1'],roles:{Entity:[0,1], 'Positive Relationship':[1],Repulsion:[2],Event:[3]}},
 {id:'deep-field',name:'Deep Field',builtIn:true,colors:['#18304b','#28617d','#52a8c8','#9d8cff','#d5efff'],roles:{Background:[0],Entity:[2],Glow:[3,4]}},
 {id:'monochrome',name:'Monochrome',builtIn:true,colors:['#18232b','#536770','#a8c1c8','#e8fbff'],roles:{Background:[0],Entity:[2,3],Glow:[3]}},
 {id:'aurora',name:'Aurora',builtIn:true,colors:['#35f0c2','#48a9ff','#9c7bff','#ff75c8','#ffe18a'],roles:{Entity:[0,1],Cluster:[2],Event:[4]}},
];
let observerPaletteLibrary:readonly Palette[]=[];
export function setObserverPaletteLibrary(palettes:readonly Palette[]):void{observerPaletteLibrary=palettes.filter(p=>!p.builtIn)}
const channelFractions=new Map<string,number>();
export function deterministicColorFraction(sourceIdentity:string,channel:string):number{const key=`${sourceIdentity}|${channel}`,cached=channelFractions.get(key);if(cached!==undefined)return cached;const digest=sha256Hex(lengthUtf8(key)),value=Number.parseInt(digest.slice(0,8),16)/0xffffffff;channelFractions.set(key,value);return value}
export function paletteChannelColor(values:Readonly<Record<string,unknown>>,role:PaletteRole,sourceIdentity:string,channel:string,explicitColor?:string):string{return paletteColor(values,role,deterministicColorFraction(sourceIdentity,channel),explicitColor)}
export function paletteHash(palette:Pick<Palette,'colors'|'roles'>):string{const canonicalRoles=Object.fromEntries(Object.entries(palette.roles??{}).sort(([a],[b])=>a.localeCompare(b)).map(([role,indexes])=>[role,[...indexes].sort((a,b)=>a-b)]));return sha256Hex(concat(...palette.colors.map(color=>lengthUtf8(color.toLowerCase())),lengthUtf8(JSON.stringify(canonicalRoles))))}
export function paletteById(id:string,custom:readonly Palette[]=[]):Palette{return [...builtInPalettes,...custom].find(p=>p.id===id)??builtInPalettes[0]!}
export function activeObserverPalette(id:string):Palette{return paletteById(id,observerPaletteLibrary)}
export interface ColorResolveRequest {readonly role?:PaletteRole;readonly deterministicValue?:number;readonly sourceIdentity?:string;readonly explicitColor?:string;readonly palette:Palette;readonly mappingMode:'Discrete'|'Continuous'|'Semantic role';readonly reverse?:boolean;readonly offset?:number;readonly quantize?:number}
export function resolvePaletteColor(request:ColorResolveRequest):string {const p=request.palette;const role=request.role&&p.roles?.[request.role];let value=request.deterministicValue; if(value===undefined&&request.explicitColor){const c=new THREE.Color(request.explicitColor);value=(c.r*.299+c.g*.587+c.b*.114)%1}value=Math.max(0,Math.min(1,value??0));if(request.reverse)value=1-value;value=(value+(request.offset??0))%1;if(value<0)value+=1;if(request.quantize&&request.quantize>1)value=Math.round(value*(request.quantize-1))/(request.quantize-1);const indexes=role?.length?role:[...p.colors.keys()];const at=request.mappingMode==='Discrete'?Math.min(indexes.length-1,Math.floor(value*indexes.length)):value*(indexes.length-1);const low=indexes[Math.floor(at)]??0,high=indexes[Math.ceil(at)]??low;if(request.mappingMode==='Semantic role')return p.colors[indexes[Math.min(indexes.length-1,Math.floor(value*indexes.length))]!]!;if(request.mappingMode==='Discrete')return p.colors[low]!;const a=new THREE.Color(p.colors[low]!),b=new THREE.Color(p.colors[high]!);return `#${a.lerp(b,at-Math.floor(at)).getHexString()}`;}
export function paletteColor(values:Readonly<Record<string,unknown>>,role:PaletteRole,deterministicValue:number,explicitColor:string|undefined,custom:readonly Palette[]=observerPaletteLibrary):string {if(values['palette.enabled']!==true)return explicitColor??'#ffffff';const id=String(values['palette.active']??'hru-default'),p=paletteById(id,custom);return resolvePaletteColor({role,deterministicValue,explicitColor,palette:p,mappingMode:(values['palette.mappingMode'] as ColorResolveRequest['mappingMode'])??'Continuous',reverse:values['palette.reverse']===true,offset:Number(values['palette.offset']??0),quantize:Number(values['palette.quantize']??0)});}
