import type { VisualConfiguration,VisualParameterDefinition,VisualValue } from './types';
export const VISUAL_SCHEMA_VERSION='hru-visual-1';
type RawParameter=Omit<VisualParameterDefinition,'category'|'subcategory'|'categoryOrder'|'sliderMin'|'sliderMax'>;
const n=(id:string,group:string,label:string,defaultValue:number,min:number,max:number,step:number,updateMode:VisualParameterDefinition['updateMode']='immediate',performanceCost:VisualParameterDefinition['performanceCost']='low',advanced=false):RawParameter=>({id,group,label,description:`Controls ${label.toLowerCase()}. Technical ID: ${id}.`,type:'number',defaultValue,min,max,step,updateMode,performanceCost,advanced});
const b=(id:string,group:string,label:string,defaultValue:boolean,updateMode:VisualParameterDefinition['updateMode']='scene-object',advanced=false):RawParameter=>({id,group,label,description:`Shows or hides ${label.toLowerCase()}. Technical ID: ${id}.`,type:'boolean',defaultValue,updateMode,performanceCost:'negligible',advanced});
const c=(id:string,group:string,label:string,defaultValue:string):RawParameter=>({id,group,label,description:`Chooses ${label.toLowerCase()}. Technical ID: ${id}.`,type:'color',defaultValue,updateMode:'immediate',performanceCost:'negligible',advanced:false});
const s=(id:string,group:string,label:string,defaultValue:string,options:readonly string[],updateMode:VisualParameterDefinition['updateMode']='immediate'):RawParameter=>({id,group,label,description:`Chooses ${label.toLowerCase()}. Technical ID: ${id}.`,type:'select',defaultValue,options,updateMode,performanceCost:'low',advanced:false});
const v=(id:string,group:string,label:string,defaultValue:readonly[number,number,number],updateMode:VisualParameterDefinition['updateMode']='scene-object'):RawParameter=>({id,group,label,description:`Controls ${label.toLowerCase()} on the X, Y, and Z axes. Technical ID: ${id}.`,type:'vector3',defaultValue,step:.1,updateMode,performanceCost:'negligible',advanced:false});
const rawVisualParameters:readonly RawParameter[]=[
c('scene.background','Scene','Background','#07090f'),b('scene.fogEnabled','Scene','Fog',true),c('scene.fogColor','Scene','Fog color','#07090f'),n('scene.fogDensity','Scene','Fog density',.025,0,.2,.001),b('scene.gridEnabled','Scene','Grid',true),n('scene.gridSize','Scene','Grid size',30,5,200,1,'geometry-rebuild','medium'),n('scene.gridDivisions','Scene','Grid divisions',30,2,200,1,'geometry-rebuild','medium'),c('scene.gridPrimary','Scene','Primary grid color','#193345'),c('scene.gridSecondary','Scene','Secondary grid color','#101923'),n('scene.gridOpacity','Scene','Grid opacity',1,0,1,.01),n('scene.worldSpread','Scene','World spread',1,.25,4,.01,'geometry-rebuild','medium'),n('scene.pixelRatioCap','Scene','Pixel ratio cap',2,.5,3,.1,'immediate','high',true),s('scene.toneMapping','Scene','Tone mapping','none',['none','linear','reinhard','aces']),n('scene.exposure','Scene','Exposure',1,.1,4,.01),
n('camera.fov','Camera & Navigation','Field of view',55,20,110,1,'scene-object'),n('camera.near','Camera & Navigation','Near clipping',.1,.01,10,.01,'scene-object'),n('camera.far','Camera & Navigation','Far clipping',200,30,1000,1,'scene-object'),b('camera.damping','Camera & Navigation','Damping',true),n('camera.dampingFactor','Camera & Navigation','Damping factor',.05,.01,.5,.01),n('camera.rotateSpeed','Camera & Navigation','Rotate speed',1,.1,5,.1),n('camera.panSpeed','Camera & Navigation','Pan speed',1,.1,5,.1),n('camera.zoomSpeed','Camera & Navigation','Zoom speed',1,.1,5,.1),b('camera.autoRotate','Camera & Navigation','Auto rotate',false),n('camera.autoRotateSpeed','Camera & Navigation','Auto rotate speed',2,-10,10,.1),
b('light.ambientEnabled','Lighting','Ambient light',true),c('light.ambientColor','Lighting','Ambient color','#6688aa'),n('light.ambientIntensity','Lighting','Ambient intensity',1.3,0,10,.05),b('light.primaryEnabled','Lighting','Primary light',true),c('light.primaryColor','Lighting','Primary color','#8bd9ff'),n('light.primaryIntensity','Lighting','Primary intensity',45,0,200,1),v('light.primaryPosition','Lighting','Primary position',[0,0,0]),b('light.fillEnabled','Lighting','Fill light',true),c('light.fillColor','Lighting','Fill color','#8055aa'),n('light.fillIntensity','Lighting','Fill intensity',12,0,100,1),v('light.fillPosition','Lighting','Fill position',[-12,8,10]),
n('entity.scale','Entities','Global entity scale',1,.1,8,.01,'scene-object'),n('entity.minTraitScale','Entities','Minimum trait scale',.18,.03,2,.01),n('entity.maxTraitScale','Entities','Maximum trait scale',.36,.05,3,.01),n('entity.brightness','Entities','Overall brightness',1,.1,4,.01),n('entity.saturation','Entities','Saturation',.72,0,1,.01),n('entity.lightness','Entities','Lightness',.55,.05,.95,.01),n('entity.opacity','Entities','Opacity',1,.05,1,.01),n('entity.metalness','Entities','Metalness',.15,0,1,.01),n('entity.roughness','Entities','Roughness',.35,0,1,.01),n('entity.emissiveMultiplier','Entities','Emissive multiplier',1,0,8,.01),n('entity.emissiveInfluence','Entities','Emissive color influence',.5,0,1,.01),n('entity.geometryDetail','Entities','Geometry detail',1,0,3,1,'geometry-rebuild','high'),n('entity.orientationInfluence','Entities','Orientation influence',1,0,1,.01,'scene-object'),n('entity.genesisMultiplier','Entities','Genesis scale multiplier',1.45,.25,4,.01,'scene-object'),n('entity.injectionMultiplier','Entities','Injection scale multiplier',1,.25,4,.01,'scene-object'),n('entity.condensationMultiplier','Entities','Condensation scale multiplier',1.3,.25,4,.01,'scene-object'),n('entity.contextAccent','Entities','Context accent strength',.45,0,2,.01),n('entity.clusterAccent','Entities','Cluster accent strength',.45,0,2,.01),b('entity.idlePulse','Entities','Idle pulse',false),n('entity.idlePulseAmount','Entities','Idle pulse amount',.05,0,.5,.01),n('entity.idlePulseSpeed','Entities','Idle pulse speed',1,.1,10,.1),
c('relationship.positiveColor','Relationships','Positive color','#52d8ff'),c('relationship.negativeColor','Relationships','Negative color','#ff4f9b'),n('relationship.weakOpacity','Relationships','Weak bond opacity',.22,0,1,.01),n('relationship.activeOpacity','Relationships','Active bond opacity',.72,0,1,.01),n('relationship.minRadius','Relationships','Minimum cylinder radius',.014,.002,.2,.001,'geometry-rebuild','medium'),n('relationship.maxRadius','Relationships','Maximum cylinder radius',.035,.002,.3,.001,'geometry-rebuild','medium'),n('relationship.activeThickness','Relationships','Active thickness multiplier',1,1,6,.1,'geometry-rebuild','medium'),n('relationship.eventBrightness','Relationships','Event pulse brightness',.9,.1,3,.01),n('relationship.eventScale','Relationships','Event pulse scale',2,.1,8,.1),n('relationship.eventDuration','Relationships','Event persistence duration',2.5,.1,10,.1),n('relationship.ghostDuration','Relationships','Dissolved ghost duration',2.5,.1,10,.1),n('relationship.ghostOpacity','Relationships','Dissolved ghost opacity',.9,0,1,.01),n('relationship.pulseSpeed','Relationships','Relationship pulse speed',1,.1,10,.1),
b('cluster.enabled','Clusters & Contexts','Cluster accents',true),c('cluster.color','Clusters & Contexts','Cluster color','#58cbe8'),n('cluster.opacity','Clusters & Contexts','Cluster opacity',.1,0,1,.01),n('cluster.scale','Clusters & Contexts','Cluster accent scale',1,.25,3,.01),b('context.enabled','Clusters & Contexts','Context accents',true),n('context.colorInfluence','Clusters & Contexts','Context color influence',1,0,1,.01),n('context.opacity','Clusters & Contexts','Context opacity',.45,0,1,.01),n('context.scale','Clusters & Contexts','Context scale',1,.25,3,.01),c('condensation.color','Clusters & Contexts','Condensation accent color','#ffd37a'),n('condensation.pulseIntensity','Clusters & Contexts','Condensation pulse intensity',1,0,4,.01),
c('selection.color','Selection','Highlight color','#ffffff'),n('selection.scale','Selection','Highlight scale',1,.5,4,.01),b('selection.pulse','Selection','Highlight pulse',true),n('selection.pulseSpeed','Selection','Highlight pulse speed',1,.1,10,.1),n('selection.dimUnselected','Selection','Dim unselected amount',0,0,.9,.01),n('selection.bondEmphasis','Selection','Selected bond emphasis',1,1,5,.1),
n('performance.observationHz','Observation & Performance','Observation refresh rate',4,1,10,1,'scene-object'),n('performance.maxGhosts','Observation & Performance','Maximum rendered event ghosts',128,0,1024,1,'scene-object','medium'),n('performance.eventCap','Observation & Performance','Event visual cap',512,16,4096,16,'scene-object','medium'),b('performance.showFps','Observation & Performance','Render FPS display',true),
s('scene.fogType','Scene','Way fog fills the observed world','exponential',['none','exponential','linear']),n('scene.fogNear','Scene','Distance where linear fog begins',18,.001,100000,.1),n('scene.fogFar','Scene','Distance where linear fog becomes opaque',120,.002,1000000,1),v('scene.worldRotation','Scene','Rotation of the observed universe',[0,0,0]),v('scene.originOffset','Scene','Visual offset of the universe origin',[0,0,0]),n('scene.gridHeight','Scene','Height of the reference grid',-12,-10000,10000,.1,'scene-object'),v('scene.gridRotation','Scene','Rotation of the reference grid',[0,0,0]),
v('entity.scaleAxes','Entities','Shape stretch applied to rendered entities',[1,1,1]),b('entity.wireframe','Entities','Wireframe surfaces on entities',false,'immediate'),b('entity.depthTest','Entities','Entity occlusion by nearer objects',true,'immediate',true),b('entity.depthWrite','Entities','Entities writing into the depth buffer',true,'immediate',true),
n('entity.minHashSmoothness','Entities','Minimum hash-derived entity smoothness',0,0,5,1,'geometry-rebuild','high'),n('entity.maxHashSmoothness','Entities','Maximum hash-derived entity smoothness',3,0,5,1,'geometry-rebuild','high'),n('entity.hashSmoothnessStrength','Entities','Strength of hash-derived smoothness variation',1,0,1,.01,'geometry-rebuild','high'),
n('relationship.radialSegments','Relationships','Roundness of rendered relationship lines',6,3,128,1,'geometry-rebuild','high',true),b('relationship.depthTest','Relationships','Relationship occlusion by nearer objects',true,'immediate',true),
n('relationship.repulsionOpacity','Relationships','Opacity of active repulsion lines',.72,0,1,.01),n('relationship.repulsionThickness','Relationships','Extra thickness of active repulsion lines',1,0,20,.1,'geometry-rebuild','medium'),
b('cluster.wireframe','Clusters & Contexts','Wireframe cluster shells',true,'geometry-rebuild'),n('cluster.segments','Clusters & Contexts','Smoothness of cluster shells',16,4,128,1,'geometry-rebuild','high',true),n('context.thickness','Clusters & Contexts','Thickness of rendered context rings',.012,.0001,100,.001,'geometry-rebuild','medium'),n('context.segments','Clusters & Contexts','Smoothness of rendered context rings',24,3,256,1,'geometry-rebuild','high',true),n('selection.opacity','Selection','Opacity of the selected-entity highlight',.75,0,1,.01),
];

const labels:Readonly<Record<string,string>>={
  'scene.background':'Color behind the observed universe','scene.fogEnabled':'Fog visible in the observed world','scene.fogColor':'Color of the world fog','scene.fogDensity':'Thickness of exponential fog','scene.gridEnabled':'Reference grid visible','scene.gridSize':'Rendered width and depth of the grid','scene.gridDivisions':'Number of grid subdivisions','scene.gridPrimary':'Color of primary grid lines','scene.gridSecondary':'Color of secondary grid lines','scene.gridOpacity':'Opacity of the rendered grid','scene.worldSpread':'Distance between hash-derived entity positions','scene.pixelRatioCap':'Maximum display resolution scale','scene.toneMapping':'Mapping from scene light to display color','scene.exposure':'Overall renderer brightness','scene.fogType':'Way fog fills the observed world','scene.fogNear':'Distance where linear fog begins','scene.fogFar':'Distance where linear fog becomes opaque','scene.worldRotation':'Rotation of the observed universe','scene.originOffset':'Visual offset of the universe origin','scene.gridHeight':'Height of the reference grid','scene.gridRotation':'Rotation of the reference grid',
  'camera.fov':'Width of the camera view','camera.near':'Nearest visible distance from the camera','camera.far':'Farthest visible distance from the camera','camera.damping':'Smooth momentum while navigating','camera.dampingFactor':'Amount of navigation smoothing','camera.rotateSpeed':'Speed of orbiting the camera','camera.panSpeed':'Speed of moving the camera sideways','camera.zoomSpeed':'Speed of moving toward or away from the universe','camera.autoRotate':'Automatically orbit the observed universe','camera.autoRotateSpeed':'Speed and direction of automatic orbiting',
  'light.ambientEnabled':'Ambient illumination visible','light.ambientColor':'Color of ambient illumination','light.ambientIntensity':'Brightness of ambient illumination','light.primaryEnabled':'Primary point light visible','light.primaryColor':'Color of the primary point light','light.primaryIntensity':'Brightness of the primary point light','light.primaryPosition':'Position of the primary point light','light.fillEnabled':'Secondary fill light visible','light.fillColor':'Color of the secondary fill light','light.fillIntensity':'Brightness of the secondary fill light','light.fillPosition':'Position of the secondary fill light',
  'entity.scale':'Rendered size of every entity','entity.minTraitScale':'Smallest hash-derived entity size','entity.maxTraitScale':'Largest hash-derived entity size','entity.brightness':'Brightness of rendered entity surfaces','entity.saturation':'Color saturation of entities','entity.lightness':'Color lightness of entities','entity.opacity':'Transparency of rendered entities','entity.metalness':'Metal-like reflection of entity surfaces','entity.roughness':'Softness of reflections on entity surfaces','entity.emissiveMultiplier':'Amount entities appear to glow','entity.emissiveInfluence':'Influence of hash-derived glow color','entity.geometryDetail':'Geometric smoothness of entity shapes','entity.orientationInfluence':'Influence of hash-derived orientation','entity.genesisMultiplier':'Relative size of genesis entities','entity.injectionMultiplier':'Relative size of injected entities','entity.condensationMultiplier':'Relative size of condensed entities','entity.contextAccent':'Strength of context color on entities','entity.clusterAccent':'Strength of cluster color on entities','entity.idlePulse':'Gentle pulsing while entities are idle','entity.idlePulseAmount':'Amount entity glow changes during idle pulsing','entity.idlePulseSpeed':'Speed of idle entity pulsing','entity.scaleAxes':'Stretch of entity shapes along each axis','entity.wireframe':'Show entity surfaces as wireframes','entity.depthTest':'Allow nearer objects to hide entities','entity.depthWrite':'Allow entities to hide objects behind them',
  'relationship.positiveColor':'Color of rendered positive relationships','relationship.negativeColor':'Color of rendered repulsion','relationship.weakOpacity':'Opacity of lines representing weak bonds','relationship.activeOpacity':'Opacity of lines representing active relationships','relationship.minRadius':'Thickness of the weakest relationship lines','relationship.maxRadius':'Thickness of the strongest relationship lines','relationship.activeThickness':'Extra thickness for active relationships','relationship.eventBrightness':'Glow of newly observed relationship events','relationship.eventScale':'Visual expansion of relationship event pulses','relationship.eventDuration':'How long new relationship events remain visible','relationship.ghostDuration':'How long dissolved relationships leave a trace','relationship.ghostOpacity':'Opacity of dissolved relationship traces','relationship.pulseSpeed':'Speed of relationship event pulsing','relationship.radialSegments':'Roundness of rendered relationship lines','relationship.depthTest':'Allow nearer objects to hide relationship lines',
  'cluster.enabled':'Cluster boundary shells visible','cluster.color':'Color of cluster boundary shells','cluster.opacity':'Opacity of cluster boundary shells','cluster.scale':'Size exaggeration of cluster boundaries','cluster.wireframe':'Show cluster boundaries as wireframes','cluster.segments':'Smoothness of cluster boundary shells','context.enabled':'Context rings visible','context.colorInfluence':'Strength of context-derived ring color','context.opacity':'Opacity of rendered context rings','context.scale':'Size exaggeration of context rings','context.thickness':'Thickness of rendered context rings','context.segments':'Smoothness of rendered context rings','condensation.color':'Color used to mark condensed entities','condensation.pulseIntensity':'Brightness of condensation formation pulses',
  'selection.color':'Color surrounding the selected entity','selection.scale':'Size of the selected-entity highlight','selection.pulse':'Pulse the selected-entity highlight','selection.pulseSpeed':'Speed of the selected-entity pulse','selection.dimUnselected':'How much unselected entities are darkened','selection.bondEmphasis':'Brightness of relationships touching the selection','selection.opacity':'Opacity of the selected-entity highlight',
  'performance.observationHz':'Times per second observation state is sampled','performance.maxGhosts':'Maximum dissolved-event traces kept visible','performance.eventCap':'Maximum simultaneous event visuals','performance.showFps':'Show render frame-rate telemetry',
};
const category=(id:string):{category:string;categoryOrder:number;subcategory?:string}=>{
  if(id.startsWith('scene.grid'))return{category:'Grid',categoryOrder:20};
  if(id.startsWith('scene.'))return{category:'Three.js World',categoryOrder:10};
  if(id.startsWith('camera.'))return{category:'Camera',categoryOrder:30};
  if(id.startsWith('light.'))return{category:'Lighting',categoryOrder:40};
  if(id.startsWith('entity.'))return{category:'Entities',categoryOrder:50,subcategory:id.includes('Smoothness')||id==='entity.geometryDetail'?'Hash-derived smoothness':id.includes('idlePulse')?'Temporal appearance':id.includes('genesis')||id.includes('injection')||id.includes('condensation')?'Provenance sizing':'Surface and form'};
  if(id.startsWith('relationship.')){const temporal=id.includes('event')||id.includes('ghost')||id.includes('pulse');const repulsion=id==='relationship.negativeColor'||id.includes('repulsion');const weak=id.includes('weak');const shared=['relationship.minRadius','relationship.maxRadius','relationship.radialSegments','relationship.depthTest'].includes(id);return{category:'Relationships',categoryOrder:60,subcategory:temporal?'Temporal / Pulse Behavior':repulsion?'Repulsion':weak?'Weak / Developing Bonds':shared?'Shared Relationship Geometry':'Positive / Active Bonds'};}
  if(id.startsWith('cluster.'))return{category:'Clusters',categoryOrder:90};
  if(id.startsWith('context.'))return{category:'Contexts',categoryOrder:100};
  if(id.startsWith('condensation.'))return{category:'Events / Persistence',categoryOrder:120};
  if(id.startsWith('selection.'))return{category:'Selection',categoryOrder:110};
  return{category:'Performance / Observation',categoryOrder:130};
};
const sliderRange=(definition:RawParameter):Pick<VisualParameterDefinition,'sliderMin'|'sliderMax'>=>definition.type==='number'?{sliderMin:definition.min,sliderMax:definition.max}:{};
const refinedLabels:Readonly<Record<string,string>>={'relationship.activeThickness':'Thickness multiplier for rendered active positive bond lines','relationship.activeOpacity':'Opacity of rendered active positive bond lines','relationship.weakOpacity':'Opacity of rendered weak or developing relationship lines','relationship.repulsionOpacity':'Opacity of rendered active repulsion geometry','relationship.repulsionThickness':'Thickness multiplier for rendered active repulsion geometry','relationship.radialSegments':'Roundness of rendered relationship lines'};
const unitBounded=(id:string)=>/(opacity|saturation|lightness|metalness|roughness|Influence|dimUnselected)$/i.test(id);
const integerIds=new Set(['scene.gridDivisions','entity.geometryDetail','relationship.radialSegments','cluster.segments','context.segments','performance.maxGhosts','performance.eventCap']);
const technicalBounds=(definition:RawParameter):Partial<VisualParameterDefinition>=>{
  if(definition.type!=='number')return{};
  if(unitBounded(definition.id))return{min:0,max:1};
  if(definition.id==='camera.near'||definition.id==='camera.far'||definition.id==='scene.fogNear'||definition.id==='scene.fogFar')return{min:.000001,max:1_000_000_000};
  if(definition.id==='camera.fov')return{min:.001,max:179.999};
  if(definition.id==='scene.pixelRatioCap')return{min:.1,max:8};
  if(definition.id==='performance.observationHz')return{min:.5,max:30};
  if(definition.id==='relationship.eventDuration'||definition.id==='relationship.ghostDuration')return{min:.001,max:undefined};
  if(definition.id==='entity.geometryDetail')return{min:0,max:5,integer:true};
  if(definition.id==='entity.minHashSmoothness'||definition.id==='entity.maxHashSmoothness')return{min:0,max:5,integer:true};
  if(definition.id==='entity.hashSmoothnessStrength')return{min:0,max:1};
  if(definition.id==='scene.gridDivisions')return{min:1,max:2000,integer:true};
  if(definition.id==='relationship.radialSegments')return{min:3,max:128,integer:true};
  if(definition.id==='cluster.segments')return{min:4,max:256,integer:true};
  if(definition.id==='context.segments')return{min:3,max:512,integer:true};
  if(definition.id==='performance.maxGhosts'||definition.id==='performance.eventCap')return{min:0,max:10000,integer:true};
  if(definition.min!==undefined&&definition.min>=0)return{min:0,max:undefined,integer:integerIds.has(definition.id)};
  return{min:undefined,max:undefined,integer:integerIds.has(definition.id)};
};
export const visualParameters:readonly VisualParameterDefinition[]=rawVisualParameters.map((definition)=>Object.freeze({...definition,...technicalBounds(definition),...category(definition.id),...sliderRange(definition),label:refinedLabels[definition.id]??labels[definition.id]??definition.label}));
export class VisualParameterRegistry{private readonly byId=new Map<string,VisualParameterDefinition>();constructor(definitions:readonly VisualParameterDefinition[]=visualParameters){for(const definition of definitions){if(this.byId.has(definition.id))throw new Error(`Duplicate visual parameter: ${definition.id}`);this.byId.set(definition.id,Object.freeze(definition));this.validate(definition.id,definition.defaultValue)}}list(){return [...this.byId.values()]}get(id:string){const found=this.byId.get(id);if(!found)throw new Error(`Unknown visual parameter: ${id}`);return found}defaults():VisualConfiguration{return Object.fromEntries(this.list().map((item)=>[item.id,item.defaultValue]))}validate(id:string,value:VisualValue,clamp=false):VisualValue{const d=this.get(id);if(d.type==='boolean'){if(typeof value!=='boolean')throw new Error(`${id} requires boolean`);return value}if(d.type==='color'){if(typeof value!=='string'||!/^#[0-9a-fA-F]{6}$/.test(value))throw new Error(`${id} requires a six-digit hexadecimal color such as #52d8ff`);return value.toLowerCase()}if(d.type==='select'){if(typeof value!=='string'||!d.options?.includes(value))throw new Error(`${id} must be one of: ${d.options?.join(', ')}`);return value}if(d.type==='vector3'){if(!Array.isArray(value)||value.length!==3||value.some((part)=>typeof part!=='number'||!Number.isFinite(part)))throw new Error(`${id} requires three finite numbers`);const vector=value as readonly number[];if(vector.some((part)=>part<(d.min??-Infinity)||part>(d.max??Infinity))&&!clamp)throw new Error(`${id} exceeds the technically safe coordinate range ${d.min} to ${d.max}`);return vector.map((part)=>Math.max(d.min??-Infinity,Math.min(d.max??Infinity,part))) as [number,number,number]}if(typeof value!=='number'||!Number.isFinite(value))throw new Error(`${id} requires a finite number; NaN and Infinity cannot be rendered`);if(d.integer&&!Number.isInteger(value))throw new Error(`${id} requires a whole number because it controls a resource count`);if((value<(d.min??-Infinity)||value>(d.max??Infinity))&&!clamp)throw new Error(`${id} is outside its technical range ${d.min??'unbounded'} to ${d.max??'unbounded'}`);return clamp?Math.max(d.min??-Infinity,Math.min(d.max??Infinity,value)):value}}
export const visualRegistry=new VisualParameterRegistry();
export function normalizeVisualConfiguration(values:Readonly<Record<string,VisualValue>>,registry=visualRegistry):VisualConfiguration{const keys=Object.keys(values);for(const key of keys)registry.get(key);const defaults=registry.defaults();const normalized=Object.fromEntries(registry.list().map((definition)=>[definition.id,registry.validate(definition.id,values[definition.id]??defaults[definition.id]!) ]));if((normalized['camera.near'] as number)>=(normalized['camera.far'] as number))throw new Error('Nearest visible camera distance must be smaller than the farthest visible distance');if((normalized['scene.fogNear'] as number)>=(normalized['scene.fogFar'] as number))throw new Error('Linear fog start distance must be smaller than its fully opaque distance');if((normalized['entity.minTraitScale'] as number)>(normalized['entity.maxTraitScale'] as number))throw new Error('Smallest hash-derived entity size cannot exceed the largest size');if((normalized['entity.minHashSmoothness'] as number)>(normalized['entity.maxHashSmoothness'] as number))throw new Error('Minimum hash-derived smoothness cannot exceed maximum hash-derived smoothness');return normalized;}
