import { useEffect, useMemo, useState, type ReactNode } from 'react';
import type { VisualLabCommand, VisualParameterDefinition, VisualValue } from './types';
import { useVisualLab } from './visual-lab-context';

export function VisualLabPanel() {
  const { state, schema, profiles, telemetry, error, clearError, execute, setValue } = useVisualLab();
  const [search, setSearch] = useState(''); const [importText, setImportText] = useState(''); const [message, setMessage] = useState('');
  const visible = useMemo(() => {
    if (!state) return [];
    const needle=search.trim().toLowerCase();
    return schema.filter((item)=>(!state.favoritesOnly||state.favorites.includes(item.id))&&(state.showAdvanced||!item.advanced)&&(!needle||`${item.label} ${item.id} ${item.category} ${item.subcategory??''} ${item.description}`.toLowerCase().includes(needle)));
  },[schema,search,state]);
  const categories=useMemo(()=>[...new Set(visible.map((item)=>item.category))].map((name)=>({name,order:visible.find((item)=>item.category===name)!.categoryOrder,items:visible.filter((item)=>item.category===name)})).sort((a,b)=>a.order-b.order),[visible]);
  if(!state)return <small>Connecting to observer controls…</small>;
  const run=async(command:VisualLabCommand)=>{try{await execute(command);setMessage('Applied');}catch(cause){setMessage(cause instanceof Error?cause.message:String(cause));}};
  return <div className="visual-sidebar">
    <div className="visual-profile-summary"><strong>{state.activeProfile}{state.dirty?' · modified':''}</strong><button title="Copy visual profile hash" onClick={()=>void navigator.clipboard.writeText(state.activeProfileHash)}>Copy hash</button><output className="digest">{state.activeProfileHash}</output></div>
    <input className="visual-search" aria-label="Search Visual Lab controls" placeholder="Search visual settings…" value={search} onChange={(event)=>setSearch(event.target.value)}/>
    <div className="visual-actions"><button disabled={!state.canUndo} onClick={()=>void run({type:'visual-lab/undo'})}>Undo</button><button disabled={!state.canRedo} onClick={()=>void run({type:'visual-lab/redo'})}>Redo</button><button onClick={()=>void run({type:'visual-lab/reset-all'})}>Reset all</button></div>
    <div className="visual-filters"><label><input type="checkbox" checked={state.favoritesOnly} onChange={(event)=>void run({type:'visual-lab/preference/set',preference:'favoritesOnly',value:event.target.checked})}/> Favorites only</label><label><input type="checkbox" checked={state.showAdvanced} onChange={(event)=>void run({type:'visual-lab/preference/set',preference:'showAdvanced',value:event.target.checked})}/> Advanced</label></div>
    {(error||message)&&<output className={error?'visual-error':'visual-status'} onClick={clearError}>{error??message}</output>}
    <div className="visual-category-list">{categories.map(({name,items})=><NestedSection key={name} title={name} count={items.length}>{groupBySubcategory(items).map(({name:subgroup,items:subitems})=>subgroup?<NestedSection key={subgroup} title={subgroup} count={subitems.length} compact>{subitems.map(renderParameter)}</NestedSection>:subitems.map(renderParameter))}<button className="visual-reset-category" onClick={()=>void Promise.all(items.map((item)=>run({type:'visual-lab/reset-parameter',id:item.id})))}>Reset category</button></NestedSection>)}</div>
    <NestedSection title="Profiles" count={profiles.length}><div className="visual-profile-tools"><label>Active visual profile<select value={state.activeProfile} onChange={(event)=>void run({type:'visual-lab/profile/load',name:event.target.value})}>{profiles.map((profile)=><option key={profile.name}>{profile.name}</option>)}</select></label><button onClick={()=>{const name=window.prompt('Profile name');if(name)void run({type:'visual-lab/profile/save',name});}}>Save current</button><button onClick={()=>{const name=window.prompt('Duplicate profile as');if(name)void run({type:'visual-lab/profile/duplicate',source:state.activeProfile,name});}}>Duplicate</button><button onClick={()=>{const name=window.prompt('Rename profile',state.activeProfile);if(name)void run({type:'visual-lab/profile/rename',source:state.activeProfile,name});}}>Rename</button><button disabled={profiles.find((profile)=>profile.name===state.activeProfile)?.builtIn} onClick={()=>void run({type:'visual-lab/profile/delete',name:state.activeProfile})}>Delete</button><div className="visual-actions"><button onClick={()=>void run({type:'visual-lab/ab/store',slot:'A'})}>Store A</button><button onClick={()=>void run({type:'visual-lab/ab/store',slot:'B'})}>Store B</button><button onClick={()=>void run({type:'visual-lab/ab/toggle'})}>Toggle A/B</button></div><small>A/B active: {state.ab.active??'none'} · {state.ab.differingParameters.length} differences</small>{state.ab.differingParameters.length>0&&<output className="visual-differences">{state.ab.differingParameters.join(', ')}</output>}<textarea aria-label="Imported visual profile JSON" placeholder="Paste profile JSON" value={importText} onChange={(event)=>setImportText(event.target.value)}/><div className="visual-actions"><button onClick={()=>void run({type:'visual-lab/profile/import',json:importText})}>Import</button><button onClick={async()=>{const json=String(await execute({type:'visual-lab/profile/export',name:state.activeProfile}));await navigator.clipboard.writeText(json);setMessage('Profile JSON copied');}}>Export</button></div></div></NestedSection>
    <NestedSection title="Renderer telemetry"><dl><dt>FPS</dt><dd>{state.values['performance.showFps']?telemetry.fps.toFixed(0):'hidden'}</dd><dt>Draw calls</dt><dd>{telemetry.drawCalls}</dd><dt>Triangles</dt><dd>{telemetry.triangles.toLocaleString()}</dd><dt>Geometries</dt><dd>{telemetry.geometries}</dd><dt>Textures</dt><dd>{telemetry.textures}</dd><dt>Entity meshes</dt><dd>{telemetry.entityMeshes}</dd><dt>Relationship meshes</dt><dd>{telemetry.relationshipMeshes}</dd></dl></NestedSection>
    <small className="visual-count">{visible.length} of {schema.length} registered parameters reachable here</small>
  </div>;

  function renderParameter(parameter:VisualParameterDefinition){return <ParameterControl key={parameter.id} parameter={parameter} value={state!.values[parameter.id]!} favorite={state!.favorites.includes(parameter.id)} onValue={(value)=>setValue(parameter.id,value,false)} onReset={()=>void run({type:'visual-lab/reset-parameter',id:parameter.id})} onFavorite={()=>void run({type:'visual-lab/favorite/toggle',id:parameter.id})}/>;}
}

function groupBySubcategory(items:readonly VisualParameterDefinition[]){const names=[...new Set(items.map((item)=>item.subcategory??''))];return names.map((name)=>({name,items:items.filter((item)=>(item.subcategory??'')===name)}));}
function NestedSection({title,count,compact=false,children}:{title:string;count?:number;compact?:boolean;children:ReactNode}){const[open,setOpen]=useState(false);return <section className={compact?'visual-nested compact':'visual-nested'}><button className="visual-nested-title" aria-expanded={open} onClick={()=>setOpen((value)=>!value)}><span>{open?'▾':'▸'} {title}</span>{count!==undefined&&<small>{count}</small>}</button>{open&&<div className="visual-nested-content">{children}<button className="visual-close-section" onClick={()=>setOpen(false)}>Close</button></div>}</section>;}

function ParameterControl({parameter,value,favorite,onValue,onReset,onFavorite}:{parameter:VisualParameterDefinition;value:VisualValue;favorite:boolean;onValue(value:VisualValue):void;onReset():void;onFavorite():void}){
  return <div className="visual-control"><div className="visual-control-heading"><button className={favorite?'favorite active':'favorite'} aria-label={`Favorite ${parameter.label}`} onClick={onFavorite}>★</button><label htmlFor={`${parameter.id}-input`}>{parameter.label}</label><button aria-label={`Reset ${parameter.label}`} onClick={onReset}>↺</button></div><p title={parameter.id}>{parameter.description}</p>{warning(parameter)}<div className="visual-input">{input()}</div><small>Default: {String(parameter.defaultValue)}</small></div>;
  function input(){if(parameter.type==='boolean')return <input id={`${parameter.id}-input`} type="checkbox" checked={value as boolean} onChange={(event)=>onValue(event.target.checked)}/>;if(parameter.type==='color')return <><input id={`${parameter.id}-input`} type="color" value={value as string} onChange={(event)=>onValue(event.target.value)}/><input aria-label={`${parameter.label} hexadecimal value`} value={value as string} onChange={(event)=>onValue(event.target.value)}/></>;if(parameter.type==='select')return <select id={`${parameter.id}-input`} value={value as string} onChange={(event)=>onValue(event.target.value)}>{parameter.options?.map((option)=><option key={option}>{option}</option>)}</select>;if(parameter.type==='vector3')return <>{(value as readonly number[]).map((part,index)=><NumberEntry key={index} label={`${parameter.label} ${'XYZ'[index]}`} value={part} step={parameter.step} onCommit={(next)=>{const vector=[...value as readonly number[]] as [number,number,number];vector[index]=next;onValue(vector);}}/>)}</>;return <><input type="range" aria-label={`${parameter.label} slider`} value={Math.max(parameter.sliderMin??-Infinity,Math.min(parameter.sliderMax??Infinity,value as number))} min={parameter.sliderMin} max={parameter.sliderMax} step={parameter.step} onChange={(event)=>onValue(Number(event.target.value))}/><NumberEntry id={`${parameter.id}-input`} label={`${parameter.label} exact value`} value={value as number} step={parameter.step} onCommit={onValue}/></>;}
}
function NumberEntry({id,label,value,step,onCommit}:{id?:string;label:string;value:number;step?:number;onCommit(value:number):void}){const[draft,setDraft]=useState(String(value));useEffect(()=>setDraft(String(value)),[value]);const commit=()=>{const next=Number(draft);if(Number.isFinite(next))onCommit(next);};return <input id={id} aria-label={label} type="number" value={draft} step={step} onChange={(event)=>setDraft(event.target.value)} onBlur={commit} onKeyDown={(event)=>{if(event.key==='Enter'){commit();event.currentTarget.blur();}}}/>;}
function warning(parameter:VisualParameterDefinition){if(parameter.updateMode==='renderer-recreation')return <div className="visual-warning">Renderer resources are recreated automatically.</div>;if(parameter.updateMode==='geometry-rebuild')return <div className="visual-warning">Affected geometry rebuilds automatically.</div>;if(parameter.performanceCost==='high')return <div className="visual-warning">High-cost visual setting.</div>;return null;}
