import {describe,expect,it} from 'vitest';import * as THREE from 'three';import {parseHashHex} from '../../../../server/law/canonical-encoding';import type {ObservationFrame} from '../../observation-types';import {visualRegistry} from '../../../visual-lab/registry';import {buildParticleField,particleSources,ParticleFieldRenderer} from './particle-field';import {particleFractions,particleSeed} from './particle-identity';import {sha256Hex} from '../shared/sha256';
const a=parseHashHex('11'.repeat(32)),b=parseHashHex('ee'.repeat(32)),zero=parseHashHex('00'.repeat(32)),pair=parseHashHex('44'.repeat(32)),cluster=parseHashHex('77'.repeat(32));
const frame=(tick=25):ObservationFrame=>({tick,stateDigest:parseHashHex(tick.toString(16).padStart(64,'0')),entities:[{hash:a,provenance:{origin:'genesis',createdAtTick:0,seed:'seed1'},createdAtTick:0,contextHash:zero,clusterHash:cluster},{hash:b,provenance:{origin:'genesis',createdAtTick:0,seed:'seed2'},createdAtTick:0,contextHash:zero,clusterHash:cluster}],bonds:[{low:a,high:b,pairHash:pair,strength:.8,classification:'active-positive'}],clusters:[{clusterHash:cluster,memberHashes:[a,b]}],condensationRecords:[]});
const config=(patch:Record<string,number|string|boolean>={})=>({...visualRegistry.defaults(),'vfx.particleField.enabled':true,'vfx.particleField.quality':'High','vfx.particleField.perTarget':8,'vfx.particleField.globalBudget':100,...patch});
describe('Particle Field v1',()=>{
 it('uses the documented SHA-256 identity and stable independent fractions',()=>{expect(sha256Hex(new TextEncoder().encode('abc'))).toBe('ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');expect(particleSeed(a,3,9)).toEqual(particleSeed(a,3,9));expect(particleFractions(a,3,9)).toEqual(particleFractions(a,3,9));expect(particleFractions(a,3,9)).not.toEqual(particleFractions(b,3,9))});
 it('reproduces exactly at the same tick regardless of render sampling',()=>{const values=config(),one=buildParticleField(frame(100),[],undefined,values),two=buildParticleField(frame(100),[],undefined,values);expect([...one.positions]).toEqual([...two.positions]);expect([...one.colors]).toEqual([...two.colors]);expect([...one.sizes]).toEqual([...two.sizes]);expect([...buildParticleField(frame(101),[],undefined,values).positions]).not.toEqual([...one.positions])});
 it('supports entity, relationship midpoint, and cluster source placement',()=>{expect(particleSources(frame(),[],undefined,config({'vfx.particleField.target':'Entities'}))).toHaveLength(2);const relationship=particleSources(frame(),[],undefined,config({'vfx.particleField.target':'Positive Bonds'}));expect(relationship).toHaveLength(1);expect(relationship[0]?.line).toBeDefined();expect(relationship[0]?.identity).toBe(pair);expect(particleSources(frame(),[],undefined,config({'vfx.particleField.target':'Clusters'}))[0]?.identity).toBe(cluster)});
 it('applies universal driver routes and weighted compositions',()=>{const entityHash=config({'vfx.particleField.route.radius.driver1':'Entity Hash','vfx.particleField.route.radius.weight1':1,'vfx.particleField.route.radius.weight2':0});const built=buildParticleField(frame(),[],undefined,entityHash);expect(built.explanations.get(a)?.effectiveRadius).not.toBe(built.explanations.get(b)?.effectiveRadius);const composed=config({'vfx.particleField.target':'Positive Bonds','vfx.particleField.route.brightness.driver1':'Pair Hash','vfx.particleField.route.brightness.weight1':.25,'vfx.particleField.route.brightness.driver2':'Absolute Bond Strength','vfx.particleField.route.brightness.weight2':.75});expect(buildParticleField(frame(),[],undefined,composed).explanations.get(pair)?.effectiveBrightness).toBeGreaterThan(0)});
 it('enforces global budget deterministically',()=>{const values=config({'vfx.particleField.perTarget':100,'vfx.particleField.globalBudget':7}),one=buildParticleField(frame(),[],undefined,values),two=buildParticleField(frame(),[],undefined,values);expect(one.requested).toBe(200);expect(one.rendered).toBe(7);expect([...one.positions]).toEqual([...two.positions]);expect([...one.explanations.values()].reduce((sum,item)=>sum+item.rendered,0)).toBe(7)});
 it('releases and replaces its single shared geometry',()=>{const parent=new THREE.Group(),renderer=new ParticleFieldRenderer(parent),values=config();renderer.configure(values);renderer.update(frame(),[]);expect(parent.children).toHaveLength(1);for(let count=4;count<10;count++)renderer.configure({...values,'vfx.particleField.perTarget':count});expect(parent.children).toHaveLength(1);renderer.configure({...values,'vfx.particleField.enabled':false});expect(parent.children).toHaveLength(0);expect(renderer.telemetry().rendered).toBe(0);renderer.dispose()});
 it('updates only from universe tick buckets, never render calls or FPS',()=>{const parent=new THREE.Group(),renderer=new ParticleFieldRenderer(parent),values=config({'vfx.particleField.updateTicks':10});renderer.configure(values);renderer.update(frame(20),[]);const points=parent.children[0] as THREE.Points,at20=points.geometry.getAttribute('position');renderer.update(frame(21),[]);expect(points.geometry.getAttribute('position')).toBe(at20);renderer.update(frame(30),[]);expect(points.geometry.getAttribute('position')).not.toBe(at20);renderer.dispose()});
});
