import type {VisualParameterDefinition} from '../../../visual-lab/types';
const base={group:'VFX',category:'Deterministic VFX',subcategory:'Particle Field',categoryOrder:125} as const;
const n=(id:string,label:string,value:number,min:number|undefined,max:number|undefined,step:number,mode:VisualParameterDefinition['updateMode']='scene-object',cost:VisualParameterDefinition['performanceCost']='medium',advanced=false,integer=false):VisualParameterDefinition=>({...base,id,label,description:`${label}. Technical ID: ${id}.`,type:'number',defaultValue:value,min,max,sliderMin:min,sliderMax:max,step,integer,updateMode:mode,performanceCost:cost,advanced});
const b=(id:string,label:string,value:boolean,mode:VisualParameterDefinition['updateMode']='scene-object'):VisualParameterDefinition=>({...base,id,label,description:`${label}. Technical ID: ${id}.`,type:'boolean',defaultValue:value,updateMode:mode,performanceCost:'low',advanced:false});
const s=(id:string,label:string,value:string,options:readonly string[],mode:VisualParameterDefinition['updateMode']='scene-object'):VisualParameterDefinition=>({...base,id,label,description:`${label}. Technical ID: ${id}.`,type:'select',defaultValue:value,options,updateMode:mode,performanceCost:'low',advanced:false});
const c=(id:string,label:string,value:string):VisualParameterDefinition=>({...base,id,label,description:`${label}. Technical ID: ${id}.`,type:'color',defaultValue:value,updateMode:'immediate',performanceCost:'low',advanced:false});
const v=(id:string,label:string,value:readonly[number,number,number]):VisualParameterDefinition=>({...base,id,label,description:`${label}. Technical ID: ${id}.`,type:'vector3',defaultValue:value,step:.05,updateMode:'scene-object',performanceCost:'medium',advanced:false});
const drivers=['Manual','Entity Hash','Context Hash','Pair Hash','Bond Strength','Absolute Bond Strength','Bond Age','Cluster Size','Cluster Age','Cluster Stability','Event Age','Event Type','Dimension'] as const;
const routeProperties=['density','radius','size','brightness','opacity','colorVariation','rotationSpeed','spread','pulseAmplitude'] as const;
const routes=routeProperties.flatMap((property)=>[s(`vfx.particleField.route.${property}.driver1`,`${property} — first deterministic driver`,'Manual',drivers),n(`vfx.particleField.route.${property}.weight1`,`${property} — weight of first driver`,1,0,1,.01),s(`vfx.particleField.route.${property}.driver2`,`${property} — second deterministic driver`,'Manual',drivers),n(`vfx.particleField.route.${property}.weight2`,`${property} — weight of second driver`,0,0,1,.01)]);
export const particleFieldParameters:readonly VisualParameterDefinition[]=[
 s('vfx.particleField.status','Particle Field module status','Functional',['Functional']),b('vfx.particleField.enabled','Show deterministic particle fields',false),s('vfx.particleField.target','Observed sources receiving particle fields','Entities',['Entities','Selected Entity','Positive Bonds','Weak Bonds','Repulsion','Relationships','Clusters','Contexts','Condensed Entities','Events']),n('vfx.particleField.globalBudget','Maximum particles rendered across all fields',12000,0,200000,100,'geometry-rebuild','high',false,true),n('vfx.particleField.perTarget','Requested particles around each source',180,0,20000,10,'geometry-rebuild','high',false,true),s('vfx.particleField.quality','Particle rendering quality','Medium',['Low','Medium','High'],'geometry-rebuild'),n('vfx.particleField.updateTicks','Universe ticks between particle buffer updates',1,1,100000,1,'scene-object','medium',false,true),n('vfx.particleField.visualSalt','Deterministic visual salt',0,0,Number.MAX_SAFE_INTEGER,1,'geometry-rebuild','low',true,true),
 n('vfx.particleField.radius','Outer radius of each particle structure',1.5,0,1000,.05),n('vfx.particleField.innerRadius','Empty radius around each source',.15,0,1000,.05),n('vfx.particleField.radialSpread','Variation across the particle radius',1,0,100,.05),n('vfx.particleField.verticalSpread','Vertical distance occupied by particles',1,0,1000,.05),n('vfx.particleField.depthSpread','Depth distance occupied by particles',1,0,1000,.05),n('vfx.particleField.spatialScale','Compression or expansion of the complete field',1,0,100,.05),v('vfx.particleField.axialStretch','Stretch of particle fields along X, Y, and Z',[1,1,1]),v('vfx.particleField.offset','Visual offset of every particle field',[0,0,0]),
 n('vfx.particleField.branches','Number of deterministic particle branches',3,1,128,1,'scene-object','medium',false,true),n('vfx.particleField.branchTightness','How tightly particles follow their branch',.65,0,20,.01),n('vfx.particleField.spiral','Amount particle branches spiral',1,-100,100,.05),n('vfx.particleField.twist','Twist applied through the height of the structure',.5,-100,100,.05),n('vfx.particleField.shellBias','Preference for particles near the outer shell',.35,-10,10,.01),n('vfx.particleField.centerBias','Preference for particles near the center',0,-10,10,.01),n('vfx.particleField.clustering','Amount particles gather into deterministic pockets',0,0,1,.01),n('vfx.particleField.disorder','Deterministic irregularity of the structure',.18,0,10,.01),s('vfx.particleField.relationshipPlacement','Placement around rendered relationships','Midpoint',['Midpoint','Along line','Around line']),s('vfx.particleField.clusterMode','Shape of cluster particle structures','Halo',['Center field','Shell','Halo','Internal volume','Orbiting structure']),
 n('vfx.particleField.minSize','Smallest rendered particle size',.035,.001,100,.001),n('vfx.particleField.maxSize','Largest rendered particle size',.11,.001,100,.001),n('vfx.particleField.opacity','Opacity of rendered particles',.72,0,1,.01),n('vfx.particleField.brightness','Brightness of rendered particles',1,0,100,.05),n('vfx.particleField.glow','Contribution of particles to bloom',1,0,100,.05),s('vfx.particleField.colorMode','Source used for particle colors','Source hash',['Entity rendered color','Source hash','Pair hash','Cluster / Context hash','Relationship polarity','Manual']),c('vfx.particleField.manualColor','Manual particle color','#7de7ff'),n('vfx.particleField.colorVariation','Hash-derived variation between particle colors',.18,0,1,.01),n('vfx.particleField.saturation','Particle color saturation',.8,0,1,.01),n('vfx.particleField.lightness','Particle color lightness',.62,0,1,.01),b('vfx.particleField.depthTest','Allow nearer objects to hide particles',true),b('vfx.particleField.depthWrite','Allow particles to hide objects behind them',false),
 n('vfx.particleField.rotationSpeed','Rotation per universe tick',.002,-10,10,.0005),n('vfx.particleField.radialDrift','Radial motion per universe tick',.001,-10,10,.0005),n('vfx.particleField.orbitalDrift','Orbital motion per universe tick',.002,-10,10,.0005),n('vfx.particleField.verticalDrift','Vertical motion per universe tick',.001,-10,10,.0005),n('vfx.particleField.turbulence','Deterministic wave displacement',.08,0,100,.01),n('vfx.particleField.pulseAmplitude','Size of deterministic particle pulsing',.12,0,100,.01),n('vfx.particleField.pulseFrequency','Pulse cycles per universe tick',.003,0,10,.0005),n('vfx.particleField.eventPersistenceTicks','Ticks event particle fields remain visible',250,0,1000000,1,'scene-object','medium',false,true),
 n('vfx.particleField.mapping.inputMin','Shared driver input mapped to the low output',0,-1000000,1000000,.01),n('vfx.particleField.mapping.inputMax','Shared driver input mapped to the high output',1,-1000000,1000000,.01),n('vfx.particleField.mapping.outputMin','Lowest multiplier produced by a route',.25,-100,100,.01),n('vfx.particleField.mapping.outputMax','Highest multiplier produced by a route',1.75,-100,100,.01),s('vfx.particleField.mapping.curve','Response curve used by particle routes','smoothstep',['linear','ease-in','ease-out','smoothstep']),b('vfx.particleField.mapping.invert','Reverse particle driver responses',false),n('vfx.particleField.mapping.quantize','Steps in particle driver responses',0,0,1024,1,'scene-object','low',true,true),
 ...routes,
];
