import type {VisualParameterDefinition} from '../../../visual-lab/types';
const base={group:'VFX',category:'Deterministic VFX',subcategory:'Vortex Field',categoryOrder:125} as const;
const n=(id:string,label:string,value:number,min:number|undefined,max:number|undefined,step:number,mode:VisualParameterDefinition['updateMode']='scene-object',cost:VisualParameterDefinition['performanceCost']='high',advanced=false,integer=false):VisualParameterDefinition=>({...base,id,label,description:`${label}. Technical ID: ${id}.`,type:'number',defaultValue:value,min,max,sliderMin:min,sliderMax:max,step,integer,updateMode:mode,performanceCost:cost,advanced});
const b=(id:string,label:string,value:boolean):VisualParameterDefinition=>({...base,id,label,description:`${label}. Technical ID: ${id}.`,type:'boolean',defaultValue:value,updateMode:'scene-object',performanceCost:'medium',advanced:false});
const s=(id:string,label:string,value:string,options:readonly string[],mode:VisualParameterDefinition['updateMode']='scene-object'):VisualParameterDefinition=>({...base,id,label,description:`${label}. Technical ID: ${id}.`,type:'select',defaultValue:value,options,updateMode:mode,performanceCost:'medium',advanced:false});
const c=(id:string,label:string,value:string):VisualParameterDefinition=>({...base,id,label,description:`${label}. Technical ID: ${id}.`,type:'color',defaultValue:value,updateMode:'immediate',performanceCost:'low',advanced:false});
const v=(id:string,label:string,value:readonly[number,number,number]):VisualParameterDefinition=>({...base,id,label,description:`${label}. Technical ID: ${id}.`,type:'vector3',defaultValue:value,step:.05,updateMode:'scene-object',performanceCost:'medium',advanced:false});
const drivers=['Manual','Entity Hash','Context Hash','Pair Hash','Bond Strength','Absolute Bond Strength','Bond Age','Cluster Size','Cluster Age','Cluster Stability','Event Age','Event Type','Dimension'] as const;
const routeProperties=['radius','height','twist','curvature','torsion','rotationSpeed','turbulence','brightness','opacity','glow','pulseAmplitude','flowSpeed'] as const;
const routes=routeProperties.flatMap((property)=>[s(`vfx.vortexField.route.${property}.driver1`,`${property} — first deterministic driver`,'Manual',drivers),n(`vfx.vortexField.route.${property}.weight1`,`${property} — first driver weight`,1,0,1,.01),s(`vfx.vortexField.route.${property}.driver2`,`${property} — second deterministic driver`,'Manual',drivers),n(`vfx.vortexField.route.${property}.weight2`,`${property} — second driver weight`,0,0,1,.01)]);
export const vortexFieldParameters:readonly VisualParameterDefinition[]=[
 s('vfx.vortexField.status','Vortex Field module status','Functional',['Functional']),b('vfx.vortexField.enabled','Show deterministic vortex fields',false),s('vfx.vortexField.target','Observed sources receiving vortex fields','Entities',['Entities','Selected Entity','Positive Bonds','Weak Bonds','Repulsion','Relationships','Clusters','Contexts','Condensed Entities','Events']),s('vfx.vortexField.quality','Vortex geometry quality','Medium',['Low','Medium','High'],'geometry-rebuild'),n('vfx.vortexField.maxFields','Maximum active vortex fields',64,0,4096,1,'geometry-rebuild','high',false,true),n('vfx.vortexField.updateTicks','Universe ticks between vortex updates',1,1,100000,1,'scene-object','high',false,true),n('vfx.vortexField.eventPersistenceTicks','Ticks positional event vortices remain visible',250,0,1000000,1,'scene-object','medium',false,true),n('vfx.vortexField.visualSalt','Deterministic vortex visual salt',0,0,Number.MAX_SAFE_INTEGER,1,'geometry-rebuild','low',true,true),
 n('vfx.vortexField.radius','Outer radius of each vortex',1.4,0,1000,.05),n('vfx.vortexField.innerRadius','Empty radius around each source',.12,0,1000,.05),n('vfx.vortexField.height','Length of the vortex field',2.5,0,1000,.05),n('vfx.vortexField.width','Width multiplier across the field',1,0,100,.05),n('vfx.vortexField.funnel','Funnel narrowing toward one end',.35,-10,10,.01),n('vfx.vortexField.taper','Radius taper along the axis',.25,-10,10,.01),n('vfx.vortexField.shellThickness','Thickness of the visible shell',.35,0,100,.01),n('vfx.vortexField.curvature','Curvature of the vortex spine',.25,-100,100,.01),n('vfx.vortexField.twist','Twist around the vortex axis',2,-100,100,.01),n('vfx.vortexField.spiralCount','Number of spiral turns',2,-100,100,.05),n('vfx.vortexField.branchCount','Deterministic vortex branches',2,1,64,1,'geometry-rebuild','high',false,true),
 n('vfx.vortexField.axisX','Base vortex axis X',0,-1,1,.01),n('vfx.vortexField.axisY','Base vortex axis Y',1,-1,1,.01),n('vfx.vortexField.axisZ','Base vortex axis Z',0,-1,1,.01),b('vfx.vortexField.sourceAligned','Align entity fields to hash orientation',true),b('vfx.vortexField.relationshipAligned','Align relationship fields to their bond axis',true),n('vfx.vortexField.radialAlignment','Align fields toward their source position',.2,0,1,.01),n('vfx.vortexField.hashOrientation','Strength of hash-derived orientation',.7,0,1,.01),
 n('vfx.vortexField.axialStretchX','Stretch along vortex X',1,0,100,.01),n('vfx.vortexField.axialStretchY','Stretch along vortex Y',1,0,100,.01),n('vfx.vortexField.axialStretchZ','Stretch along vortex Z',1,0,100,.01),n('vfx.vortexField.torsion','Relationship-driven torsion',.5,-100,100,.01),n('vfx.vortexField.radialCompression','Radial compression',0,-100,100,.01),n('vfx.vortexField.radialExpansion','Radial expansion',0,-100,100,.01),n('vfx.vortexField.verticalCompression','Vertical compression',0,-100,100,.01),n('vfx.vortexField.bend','Bend across the vortex height',.15,-100,100,.01),n('vfx.vortexField.shear','Shear across the vortex height',0,-100,100,.01),n('vfx.vortexField.waveAmplitude','Deterministic wave displacement',.12,0,100,.01),n('vfx.vortexField.waveFrequency','Deterministic wave frequency',1,-100,100,.01),n('vfx.vortexField.disorder','Hash-derived deterministic disorder',.12,0,100,.01),n('vfx.vortexField.turbulence','Turbulence-like displacement',.08,0,100,.01),
 n('vfx.vortexField.rotationSpeed','Rotation speed per universe tick',.006,-100,100,.0005),n('vfx.vortexField.axialFlow','Flow along the vortex axis',.002,-100,100,.0005),n('vfx.vortexField.radialFlow','Flow toward or away from the axis',.001,-100,100,.0005),n('vfx.vortexField.expansionSpeed','Expansion or contraction speed',.001,-100,100,.0005),n('vfx.vortexField.pulseAmplitude','Pulse amplitude',.12,0,100,.01),n('vfx.vortexField.pulseFrequency','Pulse frequency per tick',.003,-100,100,.0005),n('vfx.vortexField.precession','Axis precession per tick',.001,-100,100,.0005),n('vfx.vortexField.oscillation','Side-to-side oscillation',.1,-100,100,.01),
 n('vfx.vortexField.opacity','Opacity of vortex geometry',.55,0,1,.01),n('vfx.vortexField.brightness','Brightness of vortex geometry',1,0,100,.05),n('vfx.vortexField.glow','Bloom/emission contribution',1,0,100,.05),n('vfx.vortexField.thickness','Rendered line thickness expression',.025,.0001,100,.001,'geometry-rebuild','high'),s('vfx.vortexField.colorMode','Source used for vortex color','Entity hash',['Source entity rendered color','Entity hash','Pair hash','Context hash','Cluster hash','Relationship polarity','Relationship strength','Manual']),c('vfx.vortexField.manualColor','Manual vortex color','#b77dff'),n('vfx.vortexField.colorVariation','Hash-derived color variation',.2,0,1,.01),n('vfx.vortexField.saturation','Vortex color saturation',.85,0,1,.01),n('vfx.vortexField.lightness','Vortex color lightness',.62,0,1,.01),b('vfx.vortexField.depthTest','Allow nearer objects to hide vortex lines',true),b('vfx.vortexField.depthWrite','Allow vortex lines to write depth',false),s('vfx.vortexField.presentation','Vortex presentation','Line',['Line','Wireframe','Particle-like']),
 s('vfx.vortexField.relationshipExpression','How relationships express vortex flow','Cylindrical wrap',['Twist around bond','Flow A → B','Flow B → A','Midpoint vortex','Cylindrical wrap','Polarity-directed rotation']),s('vfx.vortexField.clusterExpression','How clusters express vortex flow','Central vortex',['Central vortex','Surrounding shell','Inward flow','Outward flow','Orbital vortex','Multiple sub-vortices']),v('vfx.vortexField.offset','Visual offset of every vortex field',[0,0,0]),
 n('vfx.vortexField.mapping.inputMin','Shared driver input mapped to the low output',0,-1000000,1000000,.01),n('vfx.vortexField.mapping.inputMax','Shared driver input mapped to the high output',1,-1000000,1000000,.01),n('vfx.vortexField.mapping.outputMin','Lowest multiplier produced by a route',.25,-100,100,.01),n('vfx.vortexField.mapping.outputMax','Highest multiplier produced by a route',1.75,-100,100,.01),s('vfx.vortexField.mapping.curve','Response curve used by vortex routes','smoothstep',['linear','ease-in','ease-out','smoothstep']),b('vfx.vortexField.mapping.invert','Reverse vortex driver responses',false),n('vfx.vortexField.mapping.quantize','Steps in vortex driver responses',0,0,1024,1,'scene-object','low',true,true),
 ...routes,
];
