import {describe,expect,it} from 'vitest';import * as THREE from 'three';import {parseHashHex} from '../../../../server/law/canonical-encoding';import type {ObservationFrame} from '../../observation-types';import {visualRegistry} from '../../../visual-lab/registry';import {buildVortexField,vortexSources,VortexFieldRenderer} from './vortex-field';
const a=parseHashHex('11'.repeat(32)),b=parseHashHex('ee'.repeat(32)),zero=parseHashHex('00'.repeat(32)),pair=parseHashHex('44'.repeat(32)),cluster=parseHashHex('77'.repeat(32));
const frame=(tick=20):ObservationFrame=>({tick,stateDigest:parseHashHex(tick.toString(16).padStart(64,'0')),entities:[{hash:a,provenance:{origin:'genesis',createdAtTick:0,seed:'seed1'},createdAtTick:0,contextHash:zero,clusterHash:cluster},{hash:b,provenance:{origin:'genesis',createdAtTick:0,seed:'seed2'},createdAtTick:0,contextHash:zero,clusterHash:cluster}],bonds:[{low:a,high:b,pairHash:pair,strength:-.8,classification:'active-repulsion'}],clusters:[{clusterHash:cluster,memberHashes:[a,b]}],condensationRecords:[]});
const config=(patch:Record<string,number|string|boolean>={})=>({...visualRegistry.defaults(),'vfx.vortexField.enabled':true,'vfx.vortexField.quality':'Low','vfx.vortexField.branchCount':1,'vfx.vortexField.maxFields':10,...patch});
describe('Vortex Field v1',()=>{
 it('is deterministic at a tick and distinguishes source identity',()=>{const values=config(),one=buildVortexField(frame(100),[],undefined,values),two=buildVortexField(frame(100),[],undefined,values);expect([...one.positions]).toEqual([...two.positions]);expect(one.explanations.get(a)?.vortexIdentity).not.toBe(one.explanations.get(b)?.vortexIdentity);expect([...buildVortexField(frame(101),[],undefined,values).positions]).not.toEqual([...one.positions])});
 it('supports entity, repulsion-axis, and cluster sources',()=>{expect(vortexSources(frame(),[],undefined,config({'vfx.vortexField.target':'Entities'}))).toHaveLength(2);const relation=vortexSources(frame(),[],undefined,config({'vfx.vortexField.target':'Repulsion'}));expect(relation[0]?.line).toBeDefined();expect(relation[0]?.identity).toBe(pair);expect(vortexSources(frame(),[],undefined,config({'vfx.vortexField.target':'Clusters'}))[0]?.identity).toBe(cluster)});
 it('routes absolute repulsion strength and enforces field budget',()=>{const values=config({'vfx.vortexField.target':'Repulsion','vfx.vortexField.route.rotationSpeed.driver1':'Absolute Bond Strength','vfx.vortexField.route.rotationSpeed.weight1':1,'vfx.vortexField.maxFields':0});expect(buildVortexField(frame(),[],undefined,values).rendered).toBe(0);const built=buildVortexField(frame(),[],undefined,{...values,'vfx.vortexField.maxFields':10});expect(built.explanations.get(pair)?.rotation).toBeGreaterThan(0)});
 it('pauses without tick changes and disposes its single batched resource',()=>{const parent=new THREE.Group(),renderer=new VortexFieldRenderer(parent),values=config();renderer.configure(values);renderer.update(frame(20),[]);expect(parent.children).toHaveLength(1);const first=(parent.children[0] as THREE.LineSegments).geometry.getAttribute('position');renderer.update(frame(20),[]);expect((parent.children[0] as THREE.LineSegments).geometry.getAttribute('position')).toBe(first);renderer.configure({...values,'vfx.vortexField.enabled':false});expect(parent.children).toHaveLength(0);expect(renderer.telemetry().rendered).toBe(0)});
});
