import * as THREE from 'three';
import type { ObservationFrame, ObservedBond, ObservedEntity } from '../../observation-types';
import type { VisualEvent } from '../../observer-state';
import type { VisualConfiguration } from '../../../visual-lab/types';
import { booleanValue, numberValue, stringValue, vectorValue } from '../../../visual-lab/configuration';
import { transformedEntityVisual } from '../../../visual-lab/transform';
import type { VfxDriverContext, VfxDriverId } from '../drivers/driver-registry';
import { composeVfxValue, type VfxContribution } from '../mappings/composition';
import type { VfxCurve } from '../mappings/mapping';
import { concat, hexBytes, lengthUtf8, sha256Bytes, sha256Hex, uint64be } from '../shared/sha256';
import type { HashHex } from '../../../shared/ids';
import { paletteColor } from '../../../visual-lab/palettes';

type Point = readonly [number, number, number];
export interface VortexSource { readonly identity: string; readonly kind: string; readonly center: Point; readonly line?: readonly [Point, Point]; readonly extent: number; readonly color: string; readonly context: VfxDriverContext }
export interface VortexExplanation { readonly sourceIdentity: string; readonly vortexIdentity: string; readonly fractions: readonly number[]; readonly radius: number; readonly twist: number; readonly rotation: number; readonly turbulence: number; readonly drivers: readonly string[] }
export interface VortexBuild { readonly positions: Float32Array; readonly colors: Float32Array; readonly requested: number; readonly rendered: number; readonly fields: number; readonly vertices: number; readonly explanations: ReadonlyMap<string, VortexExplanation> }
const empty = (): VortexBuild => ({ positions: new Float32Array(), colors: new Float32Array(), requested: 0, rendered: 0, fields: 0, vertices: 0, explanations: new Map() });
const point = (value: { x: number; y: number; z: number }): Point => [value.x, value.y, value.z];
const midpoint = (a: Point, b: Point): Point => [(a[0] + b[0]) / 2, (a[1] + b[1]) / 2, (a[2] + b[2]) / 2];
const pairIdentity = (bond: Pick<ObservedBond, 'low' | 'high' | 'pairHash'>): string => bond.pairHash ?? sha256Hex(concat(hexBytes(bond.low), hexBytes(bond.high)));
const vortexSeed = (source: string, salt: number): Uint8Array => sha256Bytes(concat(lengthUtf8('hru-vortex-field-1'), hexBytes(source), uint64be(salt)));
const fractions = (source: string, salt: number): number[] => { const bytes = vortexSeed(source, salt), view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength); return Array.from({ length: 8 }, (_, index) => view.getUint16(index * 2, false) / 65535); };

function route(property: string, values: VisualConfiguration, context: VfxDriverContext): number {
  if (!Object.keys(context).length) return 1;
  const make = (slot: 1 | 2): VfxContribution => ({ driver: stringValue(values, `vfx.vortexField.route.${property}.driver${slot}`) as VfxDriverId, weight: numberValue(values, `vfx.vortexField.route.${property}.weight${slot}`), mapping: { inputMin: numberValue(values, 'vfx.vortexField.mapping.inputMin'), inputMax: numberValue(values, 'vfx.vortexField.mapping.inputMax'), outputMin: numberValue(values, 'vfx.vortexField.mapping.outputMin'), outputMax: numberValue(values, 'vfx.vortexField.mapping.outputMax'), curve: stringValue(values, 'vfx.vortexField.mapping.curve') as VfxCurve, invert: booleanValue(values, 'vfx.vortexField.mapping.invert'), quantizeSteps: numberValue(values, 'vfx.vortexField.mapping.quantize') } });
  return composeVfxValue([make(1), make(2)], { manual: .5, dimension: 'dimension-0', ...context });
}

export function vortexSources(frame: ObservationFrame, events: readonly VisualEvent[], selected: HashHex | undefined, values: VisualConfiguration): readonly VortexSource[] {
  const target = stringValue(values, 'vfx.vortexField.target'), entities = new Map(frame.entities.map(entity => [entity.hash, entity])), positions = new Map(frame.entities.map(entity => [entity.hash, point(transformedEntityVisual(entity, values).position)])), sources: VortexSource[] = [];
  const entitySource = (entity: ObservedEntity, kind: string): VortexSource => ({ identity: entity.hash, kind, center: positions.get(entity.hash)!, extent: .4, color: transformedEntityVisual(entity, values).finalColor, context: { entityHash: entity.hash, contextHash: entity.contextHash } });
  if (target === 'Entities') for (const entity of frame.entities) sources.push(entitySource(entity, target));
  if (target === 'Selected Entity' && selected && entities.has(selected)) sources.push(entitySource(entities.get(selected)!, target));
  if (['Positive Bonds', 'Weak Bonds', 'Repulsion', 'Relationships'].includes(target)) for (const bond of frame.bonds) {
    const kind = bond.classification === 'active-positive' ? 'Positive Bonds' : bond.classification === 'active-repulsion' ? 'Repulsion' : 'Weak Bonds'; if (target !== 'Relationships' && target !== kind) continue;
    const a = positions.get(bond.low), b = positions.get(bond.high); if (!a || !b) continue; const identity = pairIdentity(bond);
    sources.push({ identity, kind, center: midpoint(a, b), line: [a, b], extent: Math.max(.4, Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]) / 2), color: stringValue(values, bond.strength >= 0 ? 'relationship.positiveColor' : 'relationship.negativeColor'), context: { pairHash: identity, bondStrength: bond.strength } });
  }
  if (target === 'Clusters') for (const cluster of frame.clusters) { const members = cluster.memberHashes.map(hash => positions.get(hash)).filter((value): value is Point => Boolean(value)); if (!members.length) continue; const center: [number, number, number] = [0, 0, 0]; for (const member of members) { center[0] += member[0]; center[1] += member[1]; center[2] += member[2]; } center[0] /= members.length; center[1] /= members.length; center[2] /= members.length; const extent = Math.max(.4, ...members.map(member => Math.hypot(member[0] - center[0], member[1] - center[1], member[2] - center[2]))); sources.push({ identity: cluster.clusterHash, kind: target, center, extent, color: stringValue(values, 'cluster.color'), context: { entityHash: cluster.clusterHash, clusterSize: members.length } }); }
  if (target === 'Contexts') for (const entity of frame.entities) if (entity.contextHash !== '0'.repeat(64)) sources.push({ ...entitySource(entity, target), identity: entity.contextHash, context: { entityHash: entity.hash, contextHash: entity.contextHash } });
  if (target === 'Condensed Entities') for (const record of frame.condensationRecords) { const entity = entities.get(record.entityHash); if (entity) sources.push({ ...entitySource(entity, target), color: stringValue(values, 'condensation.color') }); }
  if (target === 'Events') { const persistence = numberValue(values, 'vfx.particleField.eventPersistenceTicks'); for (const visual of events) { const age = frame.tick - visual.event.tick, located = visual.event.participants.map(hash => positions.get(hash)).filter((value): value is Point => Boolean(value)); if (age < 0 || age > persistence || !located.length) continue; sources.push({ identity: visual.event.eventId, kind: target, center: located.length > 1 ? midpoint(located[0]!, located[1]!) : located[0]!, line: located.length > 1 ? [located[0]!, located[1]!] : undefined, extent: .5, color: stringValue(values, visual.event.type.includes('negative') ? 'relationship.negativeColor' : 'relationship.positiveColor'), context: { eventAge: age, eventType: visual.event.type, bondStrength: visual.event.strength } }); } }
  return sources.sort((a, b) => a.identity < b.identity ? -1 : a.identity > b.identity ? 1 : a.kind < b.kind ? -1 : a.kind > b.kind ? 1 : 0);
}

function vortexColor(source: VortexSource, variation: number, values: VisualConfiguration): THREE.Color { const mode = stringValue(values, 'vfx.vortexField.colorMode'), identity = mode === 'Pair hash' ? source.context.pairHash : mode === 'Context hash' ? source.context.contextHash : mode === 'Cluster hash' ? source.context.entityHash : source.identity; let color = mode === 'Manual' ? new THREE.Color(stringValue(values, 'vfx.vortexField.manualColor')) : mode === 'Source entity rendered color' || mode === 'Relationship polarity' ? new THREE.Color(source.color) : new THREE.Color().setHSL(Number.parseInt((identity ?? source.identity).slice(0, 8), 16) / 0xffffffff, numberValue(values, 'vfx.vortexField.saturation'), numberValue(values, 'vfx.vortexField.lightness')); const hsl = { h: 0, s: 0, l: 0 }; color.getHSL(hsl); color.setHSL((hsl.h + (variation - .5) * numberValue(values, 'vfx.vortexField.colorVariation') + 1) % 1, numberValue(values, 'vfx.vortexField.saturation'), numberValue(values, 'vfx.vortexField.lightness')); return new THREE.Color(paletteColor(values,'Vortex',Number.parseInt((identity ?? source.identity).slice(0,8),16)/0xffffffff,`#${color.getHexString()}`)); }

export function buildVortexField(frame: ObservationFrame, events: readonly VisualEvent[], selected: HashHex | undefined, values: VisualConfiguration): VortexBuild {
  if (!booleanValue(values, 'vfx.vortexField.enabled')) return empty(); const sources = vortexSources(frame, events, selected, values).slice(0, numberValue(values, 'vfx.vortexField.maxFields')); const quality = ({ Low: 32, Medium: 64, High: 128 } as const)[stringValue(values, 'vfx.vortexField.quality') as 'Low' | 'Medium' | 'High'], branches = numberValue(values, 'vfx.vortexField.branchCount'), segments = sources.length * quality * branches, positions = new Float32Array(segments * 2 * 3), colors = new Float32Array(segments * 2 * 3), salt = numberValue(values, 'vfx.vortexField.visualSalt'), offset = vectorValue(values, 'vfx.vortexField.offset'), explanations = new Map<string, VortexExplanation>(); let cursor = 0;
  for (const source of sources) {
    const f = fractions(source.identity, salt), radius = numberValue(values, 'vfx.vortexField.radius') * route('radius', values, source.context), height = numberValue(values, 'vfx.vortexField.height') * route('height', values, source.context), twist = numberValue(values, 'vfx.vortexField.twist') * route('twist', values, source.context), rotation = numberValue(values, 'vfx.vortexField.rotationSpeed') * route('rotationSpeed', values, source.context), turbulence = numberValue(values, 'vfx.vortexField.turbulence') * route('turbulence', values, source.context);
    let axis: [number, number, number] = [numberValue(values, 'vfx.vortexField.axisX') + (.5 - f[2]!) * numberValue(values, 'vfx.vortexField.hashOrientation'), numberValue(values, 'vfx.vortexField.axisY') + (.5 - f[3]!) * numberValue(values, 'vfx.vortexField.hashOrientation'), numberValue(values, 'vfx.vortexField.axisZ') + (.5 - f[4]!) * numberValue(values, 'vfx.vortexField.hashOrientation')]; if (source.line && booleanValue(values, 'vfx.vortexField.relationshipAligned')) axis = [source.line[1][0] - source.line[0][0], source.line[1][1] - source.line[0][1], source.line[1][2] - source.line[0][2]]; const length = Math.max(.0001, Math.hypot(...axis)), w = axis.map(value => value / length) as [number, number, number], u0: [number, number, number] = Math.abs(w[1]) < .9 ? [-w[2], 0, w[0]] : [1, 0, 0], uLength = Math.max(.0001, Math.hypot(...u0)), u = u0.map(value => value / uLength) as [number, number, number], v: [number, number, number] = [w[1] * u[2] - w[2] * u[1], w[2] * u[0] - w[0] * u[2], w[0] * u[1] - w[1] * u[0]];
    for (let branch = 0; branch < branches; branch++) { let previous: Point | undefined; for (let segment = 0; segment < quality; segment++) { const t = segment / (quality - 1), angle = f[0]! * Math.PI * 2 + branch / branches * Math.PI * 2 + t * numberValue(values, 'vfx.vortexField.spiralCount') * Math.PI * 2 + frame.tick * rotation * (1 + f[5]!), pulse = 1 + Math.sin(frame.tick * numberValue(values, 'vfx.vortexField.pulseFrequency') * Math.PI * 2 + f[6]! * Math.PI * 2) * numberValue(values, 'vfx.vortexField.pulseAmplitude') * route('pulseAmplitude', values, source.context), radial = radius * (1 - numberValue(values, 'vfx.vortexField.funnel') * t) * (1 - numberValue(values, 'vfx.vortexField.taper') * t) * pulse * (1 + Math.sin(t * 17 + f[7]! * 20) * numberValue(values, 'vfx.vortexField.disorder')), flow = t * height + frame.tick * numberValue(values, 'vfx.vortexField.axialFlow') * route('flowSpeed', values, source.context), bend = numberValue(values, 'vfx.vortexField.curvature') * t * t, x = source.center[0] + w[0] * flow + u[0] * (Math.cos(angle + twist * t) * radial + bend) + v[0] * Math.sin(angle) * turbulence, y = source.center[1] + w[1] * flow + u[1] * (Math.cos(angle + twist * t) * radial + bend) + v[1] * Math.sin(angle) * turbulence, z = source.center[2] + w[2] * flow + u[2] * (Math.cos(angle + twist * t) * radial + bend) + v[2] * Math.sin(angle) * turbulence, next: Point = [x + offset[0], y + offset[1], z + offset[2]]; if (previous) { positions.set(previous, cursor * 3); positions.set(next, (cursor + 1) * 3); const color = vortexColor(source, f[1]!, values); color.multiplyScalar(numberValue(values, 'vfx.vortexField.brightness') * route('brightness', values, source.context) * route('opacity', values, source.context) * (.6 + .4 * f[2]!)); colors.set([color.r, color.g, color.b], cursor * 3); colors.set([color.r, color.g, color.b], (cursor + 1) * 3); cursor += 2; } previous = next; } }
    explanations.set(source.identity, { sourceIdentity: source.identity, vortexIdentity: sha256Hex(vortexSeed(source.identity, salt)), fractions: f, radius, twist, rotation, turbulence, drivers: ['radius', 'height', 'twist', 'curvature', 'torsion', 'rotationSpeed', 'turbulence', 'brightness', 'opacity', 'glow', 'pulseAmplitude', 'flowSpeed'].flatMap(property => [stringValue(values, `vfx.vortexField.route.${property}.driver1`), ...(numberValue(values, `vfx.vortexField.route.${property}.weight2`) > 0 ? [stringValue(values, `vfx.vortexField.route.${property}.driver2`)] : [])]) });
  }
  const globalGlow = numberValue(values, 'vfx.vortexField.glow'); for (let index = 0; index < colors.length; index++) colors[index] = colors[index]! * (1 + globalGlow);
  return { positions, colors, requested: sources.length, rendered: sources.length, fields: sources.length, vertices: cursor * 2, explanations };
}

export interface VortexTelemetry { readonly requested: number; readonly rendered: number; readonly vertices: number; readonly drawCalls: number; readonly buffers: number; readonly updateTicks: number; readonly cpuMilliseconds: number }
export class VortexFieldRenderer {
  private lines?: THREE.LineSegments; private values?: VisualConfiguration; private frame?: ObservationFrame; private events: readonly VisualEvent[] = []; private selected?: HashHex; private data: VortexBuild = empty(); private bucket = -1; private signature = ''; private cpu = 0;
  constructor(private readonly parent: THREE.Object3D) {}
  configure(values: VisualConfiguration) { this.values = values; this.rebuild(true); }
  update(frame: ObservationFrame, events: readonly VisualEvent[], selected?: HashHex) { this.frame = frame; this.events = events; this.selected = selected; const interval = this.values ? numberValue(this.values, 'vfx.vortexField.updateTicks') : 1, bucket = Math.floor(frame.tick / interval), signature = `${frame.stateDigest}|${events.map(event => event.event.eventId).join(',')}`; if (bucket !== this.bucket || signature !== this.signature) { this.rebuild(signature !== this.signature); this.bucket = bucket; this.signature = signature; } }
  setSelection(selected?: HashHex) { this.selected = selected; this.rebuild(true); }
  explanation(identity: string) { return this.data.explanations.get(identity); }
  telemetry(): VortexTelemetry { return { requested: this.data.requested, rendered: this.data.rendered, vertices: this.data.vertices, drawCalls: this.lines ? 1 : 0, buffers: this.lines ? 1 : 0, updateTicks: this.values ? numberValue(this.values, 'vfx.vortexField.updateTicks') : 0, cpuMilliseconds: this.cpu }; }
  dispose() { if (this.lines) { this.parent.remove(this.lines); this.lines.geometry.dispose(); (this.lines.material as THREE.Material).dispose(); this.lines = undefined; } this.data = empty(); }
  private rebuild(force: boolean) { if (!this.values || !this.frame || !booleanValue(this.values, 'vfx.vortexField.enabled')) { this.dispose(); return; } const started = performance.now(), next = buildVortexField(this.frame, this.events, this.selected, this.values); if (this.lines && this.data.vertices === next.vertices && !force) { this.lines.geometry.setAttribute('position', new THREE.BufferAttribute(next.positions, 3)); this.lines.geometry.setAttribute('color', new THREE.BufferAttribute(next.colors, 3)); } else { this.dispose(); const geometry = new THREE.BufferGeometry(); geometry.setAttribute('position', new THREE.BufferAttribute(next.positions, 3)); geometry.setAttribute('color', new THREE.BufferAttribute(next.colors, 3)); const material = new THREE.LineBasicMaterial({ vertexColors: true, transparent: true, opacity: numberValue(this.values, 'vfx.vortexField.opacity'), depthTest: booleanValue(this.values, 'vfx.vortexField.depthTest'), depthWrite: booleanValue(this.values, 'vfx.vortexField.depthWrite'), blending: THREE.AdditiveBlending, toneMapped: false }); this.lines = new THREE.LineSegments(geometry, material); this.lines.name = 'vfx:vortex-field'; this.parent.add(this.lines); } this.data = next; this.cpu = performance.now() - started; }
}
