import * as THREE from 'three';
import {EffectComposer} from 'three/examples/jsm/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/examples/jsm/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/examples/jsm/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/examples/jsm/postprocessing/OutputPass.js';
import {BokehPass} from 'three/examples/jsm/postprocessing/BokehPass.js';
import type {VisualConfiguration} from '../../../visual-lab/types';import {booleanValue,numberValue,stringValue} from '../../../visual-lab/configuration';
import type {VfxTelemetry} from '../shared/types';
import {RadialBlurPass,aggregateRadialBlur} from './radial-blur';
import type {ObservationFrame} from '../../observation-types';
import type {VisualEvent} from '../../observer-state';
import type {HashHex} from '../../../shared/ids';
import {dimensionZeroPosition} from '../../dimension-0';

export class BloomPipeline{
 private composer?:EffectComposer;private bloom?:UnrealBloomPass;private radial?:RadialBlurPass;private dof?:BokehPass;private width=1;private height=1;private quality='';private enabledEffects=0; private radialRequested=0; private radialSamples=0; private dofFocus=30;
 constructor(private readonly renderer:THREE.WebGLRenderer,private readonly scene:THREE.Scene,private readonly camera:THREE.Camera){}
 configure(values:VisualConfiguration):void{const bloomEnabled=booleanValue(values,'vfx.bloom.enabled'),selectiveEnabled=booleanValue(values,'vfx.selective.enabled'),radialEnabled=booleanValue(values,'vfx.radialBlur.enabled'),dofEnabled=booleanValue(values,'camera.dof.enabled'),enabled=bloomEnabled||selectiveEnabled||radialEnabled||dofEnabled;const quality=dofEnabled?stringValue(values,'camera.dof.quality'):radialEnabled?stringValue(values,'vfx.radialBlur.quality'):selectiveEnabled?stringValue(values,'vfx.selective.quality'):stringValue(values,'vfx.bloom.quality');if(!enabled){this.dispose();return}if(this.composer&&quality!==this.quality)this.dispose();if(!this.composer){this.quality=quality;this.composer=new EffectComposer(this.renderer);this.composer.setPixelRatio(this.renderer.getPixelRatio()*({Low:.5,Medium:.75,High:1}[quality as 'Low'|'Medium'|'High']??.75));this.composer.addPass(new RenderPass(this.scene,this.camera));if(dofEnabled){this.dof=new BokehPass(this.scene,this.camera,{focus:numberValue(values,'camera.dof.focusDistance'),aperture:numberValue(values,'camera.dof.blurAmount')*.0001,maxblur:numberValue(values,'camera.dof.maxBlur')});this.composer.addPass(this.dof);}if(radialEnabled){this.radial=new RadialBlurPass();this.composer.addPass(this.radial);}if(bloomEnabled||selectiveEnabled){this.bloom=new UnrealBloomPass(new THREE.Vector2(this.width,this.height),1,.1,.8);this.composer.addPass(this.bloom);}this.composer.addPass(new OutputPass());this.composer.setSize(this.width,this.height)}this.enabledEffects=Number(bloomEnabled)+Number(selectiveEnabled)+Number(radialEnabled)+Number(dofEnabled);if(this.bloom){this.bloom.strength=bloomEnabled?numberValue(values,'vfx.bloom.strength'):1;this.bloom.radius=numberValue(values,'vfx.bloom.radius');this.bloom.threshold=numberValue(values,'vfx.bloom.threshold');}if(this.dof){this.dof.materialBokeh.uniforms.focus.value=this.dofFocus;this.dof.materialBokeh.uniforms.aperture.value=numberValue(values,'camera.dof.blurAmount')*.0001;this.dof.materialBokeh.uniforms.maxblur.value=numberValue(values,'camera.dof.maxBlur');}}
 setDofFocus(frame:ObservationFrame|undefined,selected:HashHex|undefined,values:VisualConfiguration|undefined):void{if(!this.dof||!frame||!values)return;let target:THREE.Vector3|undefined;const mode=stringValue(values,'camera.dof.focusMode');if(mode==='Selected Entity'&&selected){const e=frame.entities.find(x=>x.hash===selected);if(e){const p=dimensionZeroPosition(e.hash),s=numberValue(values,'scene.worldSpread');target=new THREE.Vector3(p.x*s,p.y*s,p.z*s);}}else if(mode==='Selected Entity cluster'&&selected){const e=frame.entities.find(x=>x.hash===selected),cluster=e?.clusterHash&&frame.clusters.find(c=>c.clusterHash===e.clusterHash);if(cluster){const pts=cluster.memberHashes.map(h=>{const p=dimensionZeroPosition(h),s=numberValue(values,'scene.worldSpread');return new THREE.Vector3(p.x*s,p.y*s,p.z*s)});target=pts.reduce((a,p)=>a.add(p),new THREE.Vector3()).multiplyScalar(1/pts.length);}}if(!target&&mode==='Largest visible cluster'&&frame.clusters.length){const c=[...frame.clusters].sort((a,b)=>b.memberHashes.length-a.memberHashes.length||a.clusterHash.localeCompare(b.clusterHash))[0]!;const pts=c.memberHashes.map(h=>{const p=dimensionZeroPosition(h),s=numberValue(values,'scene.worldSpread');return new THREE.Vector3(p.x*s,p.y*s,p.z*s)});target=pts.reduce((a,p)=>a.add(p),new THREE.Vector3()).multiplyScalar(1/pts.length);}if(!target&&mode==='Nearest rendered entity'){let best=Infinity;for(const e of frame.entities){const p=dimensionZeroPosition(e.hash),s=numberValue(values,'scene.worldSpread'),q=new THREE.Vector3(p.x*s,p.y*s,p.z*s),d=q.distanceTo(this.camera.position);if(d<best){best=d;target=q}}}this.dofFocus=target?target.distanceTo(this.camera.position):numberValue(values,'camera.dof.focusDistance');this.dof.materialBokeh.uniforms.focus.value=this.dofFocus;}
 setRadialState(frame:ObservationFrame|undefined,events:readonly VisualEvent[],selected:HashHex|undefined,values:VisualConfiguration|undefined):void{if(!this.radial||!frame||!values){this.radial?.setAggregate(undefined);this.radialRequested=0;this.radialSamples=0;return}const aggregate=aggregateRadialBlur(frame,events,selected,this.camera,values);this.radial.setAggregate(aggregate);this.radialRequested=aggregate.requested;this.radialSamples=aggregate.samples;}
 setSize(width:number,height:number){this.width=width;this.height=height;this.composer?.setSize(width,height)}
 render(){if(this.composer)this.composer.render();else this.renderer.render(this.scene,this.camera)}
 telemetry():VfxTelemetry{return{activeEffects:this.enabledEffects,postprocessingPasses:this.composer?(this.radial?4:3):0,particles:0,geometries:0,drawCalls:this.composer?1:0,estimatedCost:this.composer?'medium':'none',radialRequested:this.radialRequested,radialRendered:this.radial?.enabled?this.radialRequested:0,radialSamples:this.radial?.enabled?this.radialSamples:0}}
 dispose(){this.composer?.dispose();this.bloom?.dispose();this.radial?.dispose();this.dof?.dispose();this.composer=undefined;this.bloom=undefined;this.radial=undefined;this.dof=undefined;this.enabledEffects=0;this.radialRequested=0}
}
