import type {VisualParameterDefinition} from '../../../visual-lab/types';
const base={group:'VFX',category:'Deterministic VFX',subcategory:'Radial Blur',categoryOrder:126} as const;
const n=(id:string,label:string,value:number,min:number,max:number,step:number,mode:VisualParameterDefinition['updateMode']='immediate',cost:VisualParameterDefinition['performanceCost']='medium'):VisualParameterDefinition=>({...base,id,label,description:`${label}. Technical ID: ${id}.`,type:'number',defaultValue:value,min,max,sliderMin:min,sliderMax:max,step,updateMode:mode,performanceCost:cost,advanced:false});
const b=(id:string,label:string,value:boolean):VisualParameterDefinition=>({...base,id,label,description:`${label}. Technical ID: ${id}.`,type:'boolean',defaultValue:value,updateMode:'immediate',performanceCost:'low',advanced:false});
const s=(id:string,label:string,value:string,options:readonly string[],mode:VisualParameterDefinition['updateMode']='immediate'):VisualParameterDefinition=>({...base,id,label,description:`${label}. Technical ID: ${id}.`,type:'select',defaultValue:value,options,updateMode:mode,performanceCost:'medium',advanced:false});
const drivers=['Manual','Entity Hash','Context Hash','Pair Hash','Bond Strength','Absolute Bond Strength','Bond Age','Cluster Size','Cluster Age','Cluster Stability','Event Age','Event Type','Dimension'] as const;
const routes=['strength','radius','decay','duration','exposure','pulseAmplitude'].flatMap((p)=>[s(`vfx.radialBlur.route.${p}.driver1`,`${p} first driver`,'Manual',drivers),n(`vfx.radialBlur.route.${p}.weight1`,`${p} first driver weight`,1,0,1,.01),s(`vfx.radialBlur.route.${p}.driver2`,`${p} second driver`,'Manual',drivers),n(`vfx.radialBlur.route.${p}.weight2`,`${p} second driver weight`,0,0,1,.01)]);
export const radialBlurParameters:readonly VisualParameterDefinition[]=[
 s('vfx.radialBlur.status','Radial Blur module status','Functional',['Functional']),b('vfx.radialBlur.enabled','Briefly distort the observer view around qualifying events',false),s('vfx.radialBlur.sourceMode','Event source selection','Observation events',['Observation events','Manual','All available sources']),s('vfx.radialBlur.quality','Radial distortion quality','Medium',['Low','Medium','High'],'geometry-rebuild'),n('vfx.radialBlur.maxEvents','Maximum simultaneous blur events',4,0,64,1,'scene-object','high'),n('vfx.radialBlur.updateTicks','Universe ticks between blur updates',1,1,100000,1,'scene-object','medium'),n('vfx.radialBlur.visualSalt','Deterministic blur visual salt',0,0,Number.MAX_SAFE_INTEGER,1,'immediate','low'),
 n('vfx.radialBlur.strength','Strength of the radial visual distortion',.35,0,10,.01),n('vfx.radialBlur.radius','Reach of the radial distortion',.25,0,10,.01),n('vfx.radialBlur.decay','How quickly samples fade through the blur',.85,0,2,.01),n('vfx.radialBlur.exposure','Brightness contribution from the distortion',.1,-10,10,.01),n('vfx.radialBlur.samples','Samples used for radial blur',16,1,64,1,'geometry-rebuild','high'),n('vfx.radialBlur.centerFalloff','Falloff around each event center',1,0,10,.01),n('vfx.radialBlur.edgeFalloff','Falloff toward the viewport edge',2,0,10,.01),n('vfx.radialBlur.brightnessResponse','Response to bright source imagery',1,0,10,.01),
 n('vfx.radialBlur.durationTicks','Event duration in universe ticks',30,0,1000000,1),n('vfx.radialBlur.attackTicks','Attack duration in ticks',2,0,1000000,1),n('vfx.radialBlur.holdTicks','Hold duration in ticks',4,0,1000000,1),n('vfx.radialBlur.decayTicks','Decay duration in ticks',24,0,1000000,1),n('vfx.radialBlur.pulseCount','Number of deterministic pulses',1,0,32,1),n('vfx.radialBlur.pulseSpacing','Ticks between pulses',4,0,1000000,1),n('vfx.radialBlur.pulseVariation','Deterministic pulse strength variation',.2,-10,10,.01),
 n('vfx.radialBlur.centerOffsetX','Horizontal event-center offset',0,-100,100,.01),n('vfx.radialBlur.centerOffsetY','Vertical event-center offset',0,-100,100,.01),n('vfx.radialBlur.radialExpansion','Outward expansion of the distortion',0,-100,100,.01),n('vfx.radialBlur.radialContraction','Inward contraction of the distortion',0,-100,100,.01),b('vfx.radialBlur.centerFollow','Follow moving observer centers',true),n('vfx.radialBlur.manualX','Manual blur center horizontal position',.5,-100,100,.01),n('vfx.radialBlur.manualY','Manual blur center vertical position',.5,-100,100,.01),
 b('vfx.radialBlur.trigger.positiveCreated','Trigger on positive bond creation',true),b('vfx.radialBlur.trigger.negativeCreated','Trigger on negative or repulsive bond creation',true),b('vfx.radialBlur.trigger.bondDissolved','Trigger when a bond dissolves',true),b('vfx.radialBlur.trigger.condensation','Trigger when an entity condenses',true),b('vfx.radialBlur.trigger.clusterEvent','Trigger on cluster formation or dissolution',true),b('vfx.radialBlur.trigger.selected','Trigger around the selected entity',false),b('vfx.radialBlur.trigger.manual','Trigger a manual observer center',false),
 n('vfx.radialBlur.mapping.inputMin','Driver input minimum',0,-1000000,1000000,.01),n('vfx.radialBlur.mapping.inputMax','Driver input maximum',1,-1000000,1000000,.01),n('vfx.radialBlur.mapping.outputMin','Mapped output minimum',0,-100,100,.01),n('vfx.radialBlur.mapping.outputMax','Mapped output maximum',1,-100,100,.01),s('vfx.radialBlur.mapping.curve','Driver response curve','smoothstep',['linear','ease-in','ease-out','smoothstep']),b('vfx.radialBlur.mapping.invert','Invert driver response',false),n('vfx.radialBlur.mapping.quantize','Driver response steps',0,0,1024,1,'immediate','low'),
 ...routes];
