import * as THREE from 'three';
import { Pass } from 'three/examples/jsm/postprocessing/Pass.js';
import type { ObservationFrame, RelationshipEvent } from '../../observation-types';
import type { VisualEvent } from '../../observer-state';
import type { HashHex } from '../../../shared/ids';
import { dimensionZeroPosition } from '../../dimension-0';
import { sha256Hex, lengthUtf8, uint64be, concat, hexBytes } from '../shared/sha256';
import { booleanValue, numberValue, stringValue } from '../../../visual-lab/configuration';
import type { VisualConfiguration } from '../../../visual-lab/types';
import {composeVfxValue} from '../mappings/composition';
import type {VfxDriverContext,VfxDriverId} from '../drivers/driver-registry';

export interface RadialBlurEvent { readonly id:string; readonly tick:number; readonly center:THREE.Vector3; readonly strength:number; readonly age:number; readonly context:VfxDriverContext; }
export interface RadialBlurAggregate { readonly events:readonly RadialBlurEvent[]; readonly center:THREE.Vector2; readonly strength:number; readonly radius:number; readonly samples:number; readonly exposure:number; readonly decay:number; readonly edgeFalloff:number; readonly brightness:number; readonly requested:number; }

const triggerFor=(type:RelationshipEvent['type'],v:VisualConfiguration)=> type==='positive-bond-created'?booleanValue(v,'vfx.radialBlur.trigger.positiveCreated'):type==='negative-bond-created'?booleanValue(v,'vfx.radialBlur.trigger.negativeCreated'):type==='bond-dissolved'?booleanValue(v,'vfx.radialBlur.trigger.bondDissolved'):type==='entity-condensed'?booleanValue(v,'vfx.radialBlur.trigger.condensation'):type.startsWith('cluster-')?booleanValue(v,'vfx.radialBlur.trigger.clusterEvent'):false;
function world(frame:ObservationFrame,hash:HashHex,v:VisualConfiguration):THREE.Vector3|undefined { const e=frame.entities.find(x=>x.hash===hash); if(!e)return; const p=dimensionZeroPosition(hash); const s=numberValue(v,'scene.worldSpread'); return new THREE.Vector3(p.x*s,p.y*s,p.z*s); }
export function radialBlurEvents(frame:ObservationFrame, visual:readonly VisualEvent[], selected:HashHex|undefined, v:VisualConfiguration):readonly RadialBlurEvent[]{
 const out:RadialBlurEvent[]=[];
 for(const item of visual){const e=item.event;if(!triggerFor(e.type,v))continue;const age=frame.tick-e.tick;const duration=Math.max(0,numberValue(v,'vfx.radialBlur.durationTicks'));if(age<0||age>duration)continue;const points=e.participants.map(h=>world(frame,h,v)).filter((p):p is THREE.Vector3=>Boolean(p));if(!points.length)continue;const c=points.length>1?points[0]!.clone().add(points[1]!).multiplyScalar(.5):points[0]!.clone();const id=sha256Hex(concat(lengthUtf8('hru-radial-blur-1'),hexBytes(e.eventId),uint64be(e.tick),uint64be(numberValue(v,'vfx.radialBlur.visualSalt'))));out.push({id,tick:e.tick,center:c,strength:Math.abs(e.strength??1),age,context:{manual:1,pairHash:e.eventId,bondStrength:e.strength,eventAge:age,eventType:e.type,dimension:'dimension-0'}});}
 if(booleanValue(v,'vfx.radialBlur.trigger.selected')&&selected){const p=world(frame,selected,v);if(p){const id=sha256Hex(concat(lengthUtf8('hru-radial-blur-1'),hexBytes(selected),uint64be(frame.tick),uint64be(numberValue(v,'vfx.radialBlur.visualSalt'))));out.push({id,tick:frame.tick,center:p,strength:1,age:0,context:{manual:1,entityHash:selected,dimension:'dimension-0'}});}}
 if(booleanValue(v,'vfx.radialBlur.trigger.manual')){out.push({id:sha256Hex(concat(lengthUtf8('hru-radial-blur-1'),lengthUtf8('manual'),uint64be(frame.tick),uint64be(numberValue(v,'vfx.radialBlur.visualSalt')))),tick:frame.tick,center:new THREE.Vector3(numberValue(v,'vfx.radialBlur.manualX'),numberValue(v,'vfx.radialBlur.manualY'),0),strength:1,age:0,context:{manual:1,dimension:'dimension-0'}});}
 return out.sort((a,b)=>b.strength-a.strength||a.id.localeCompare(b.id)).slice(0,Math.max(0,Math.floor(numberValue(v,'vfx.radialBlur.maxEvents'))));
}
function route(v:VisualConfiguration,property:string,context:VfxDriverContext,base:number):number { const driver=(id:string)=>stringValue(v,`vfx.radialBlur.route.${property}.${id}`) as VfxDriverId; const mapping={inputMin:numberValue(v,'vfx.radialBlur.mapping.inputMin'),inputMax:numberValue(v,'vfx.radialBlur.mapping.inputMax'),outputMin:numberValue(v,'vfx.radialBlur.mapping.outputMin'),outputMax:numberValue(v,'vfx.radialBlur.mapping.outputMax'),curve:stringValue(v,'vfx.radialBlur.mapping.curve') as 'linear'|'ease-in'|'ease-out'|'smoothstep',invert:booleanValue(v,'vfx.radialBlur.mapping.invert'),quantizeSteps:numberValue(v,'vfx.radialBlur.mapping.quantize')}; const mapped=composeVfxValue([{driver:driver('driver1'),weight:numberValue(v,`vfx.radialBlur.route.${property}.weight1`),mapping},{driver:driver('driver2'),weight:numberValue(v,`vfx.radialBlur.route.${property}.weight2`),mapping}],context); return (driver('driver1')==='Manual'&&driver('driver2')==='Manual')?base:base*mapped; }
export function aggregateRadialBlur(frame:ObservationFrame, visual:readonly VisualEvent[], selected:HashHex|undefined, camera:THREE.Camera, v:VisualConfiguration):RadialBlurAggregate { const events=radialBlurEvents(frame,visual,selected,v); const requested=events.length; if(!events.length)return {events,center:new THREE.Vector2(.5,.5),strength:0,radius:0,samples:0,exposure:0,decay:1,edgeFalloff:1,brightness:1,requested}; let total=0,x=0,y=0,strength=0,radius=0,exposure=0,decay=0;for(const e of events){const p=e.center.clone().project(camera);const w=Math.max(.001,e.strength);x+=(p.x*.5+.5)*w;y+=(p.y*.5+.5)*w;total+=w;strength=Math.max(strength,route(v,'strength',e.context,numberValue(v,'vfx.radialBlur.strength')));radius=Math.max(radius,route(v,'radius',e.context,numberValue(v,'vfx.radialBlur.radius')));exposure=Math.max(exposure,route(v,'exposure',e.context,numberValue(v,'vfx.radialBlur.exposure')));decay=Math.max(decay,route(v,'decay',e.context,numberValue(v,'vfx.radialBlur.decay')));}return {events,center:new THREE.Vector2(x/total,y/total),strength,radius,samples:Math.max(1,Math.min(64,Math.floor(numberValue(v,'vfx.radialBlur.samples')))),exposure,decay,edgeFalloff:numberValue(v,'vfx.radialBlur.edgeFalloff'),brightness:numberValue(v,'vfx.radialBlur.brightnessResponse'),requested}; }

export class RadialBlurPass extends Pass {
 private readonly material:THREE.ShaderMaterial; private readonly scene=new THREE.Scene(); private readonly camera=new THREE.OrthographicCamera(-1,1,1,-1,0,1); private readonly quad:THREE.Mesh; private aggregate?:RadialBlurAggregate;
 constructor(){super();this.needsSwap=true;this.material=new THREE.ShaderMaterial({uniforms:{tDiffuse:{value:null},center:{value:new THREE.Vector2(.5,.5)},strength:{value:0},radius:{value:0},samples:{value:16},exposure:{value:0},decay:{value:1},edgeFalloff:{value:1},brightness:{value:1}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform sampler2D tDiffuse;uniform vec2 center;uniform float strength,radius,samples,exposure,decay,edgeFalloff,brightness;varying vec2 vUv;void main(){vec2 d=vUv-center;float dist=length(d);float fall=pow(max(0.0,1.0-dist*edgeFalloff),2.0);vec4 c=vec4(0.0);float w=0.0;for(int i=0;i<64;i++){if(float(i)>=samples)break;float t=float(i)/max(1.0,samples-1.0);c+=texture2D(tDiffuse,vUv-d*t*radius)*pow(decay,t*8.0);w+=pow(decay,t*8.0);}c/=max(.001,w);gl_FragColor=mix(texture2D(tDiffuse,vUv),c*(1.0+exposure)*brightness,strength*fall);}' });this.quad=new THREE.Mesh(new THREE.PlaneGeometry(2,2),this.material);this.scene.add(this.quad);}
 setAggregate(a:RadialBlurAggregate|undefined){this.aggregate=a;this.enabled=Boolean(a&&a.strength>0&&a.events.length);if(a){Object.assign(this.material.uniforms,{center:{value:a.center},strength:{value:Math.min(1,Math.max(0,a.strength))},radius:{value:a.radius},samples:{value:a.samples},exposure:{value:a.exposure},decay:{value:a.decay},edgeFalloff:{value:a.edgeFalloff},brightness:{value:a.brightness}});}}
 render(renderer:THREE.WebGLRenderer,writeBuffer:THREE.WebGLRenderTarget,readBuffer:THREE.WebGLRenderTarget){this.material.uniforms.tDiffuse.value=readBuffer.texture;renderer.setRenderTarget(this.renderToScreen?null:writeBuffer);renderer.render(this.scene,this.camera);}
 dispose(){this.material.dispose();this.quad.geometry.dispose();}
}
