import { describe, expect, it } from 'vitest';
import * as THREE from 'three';
import { parseHashHex } from '../../../server/law/canonical-encoding';
import { renderChannels } from '../render-channels';
import { InstanceSelectionMap, ThreeObservationRenderer, applyChannelVisibility } from './renderer-adapter';
import { visualRegistry } from '../../visual-lab/registry';
import type { ObservationFrame } from '../observation-types';

describe('renderer adapter boundaries',()=>{
  it('applies render-channel state to scene groups',()=>{const groups=Object.fromEntries(renderChannels.map((channel)=>[channel.id,new THREE.Group()])) as unknown as Parameters<typeof applyChannelVisibility>[0];const channels=Object.fromEntries(renderChannels.map((channel)=>[channel.id,channel.id==='entities'])) as Parameters<typeof applyChannelVisibility>[1];applyChannelVisibility(groups,channels);expect(groups.entities.visible).toBe(true);expect(groups['positive-bonds'].visible).toBe(false);});
  it('maps an instanced selection to the correct entity',()=>{const map=new InstanceSelectionMap();const mesh=new THREE.InstancedMesh(new THREE.SphereGeometry(),new THREE.MeshBasicMaterial(),2);const hash=parseHashHex('ab'.repeat(32));map.set(mesh,1,hash);expect(map.get(mesh,1)).toBe(hash);expect(map.get(mesh,0)).toBeUndefined();});
  it('applies material settings without geometry rebuild and rebuilds only for geometry detail',()=>{const adapter=new ThreeObservationRenderer(new THREE.Scene());const base=visualRegistry.defaults();expect(adapter.setVisualConfiguration({...base,'scene.exposure':2}).geometryRebuilt).toBe(false);const revision=adapter.debugGeometryRevision();expect(adapter.setVisualConfiguration({...base,'entity.geometryDetail':2}).geometryRebuilt).toBe(true);expect(adapter.debugGeometryRevision()).toBe(revision+1);adapter.dispose();});
  it('reconstructs grid resources in place without accumulating scene objects',()=>{const scene=new THREE.Scene();const adapter=new ThreeObservationRenderer(scene);const base=visualRegistry.defaults();for(let size=31;size<41;size+=1)adapter.setVisualConfiguration({...base,'scene.gridSize':size});expect(scene.getObjectByName('observation:dimension-effects')?.children).toHaveLength(1);expect(scene.children.filter((child)=>child.name.startsWith('observation:'))).toHaveLength(renderChannels.length);adapter.dispose();expect(scene.children.filter((child)=>child.name.startsWith('observation:'))).toHaveLength(0);});
  it('rebuilds hash-smoothness geometries without retaining obsolete cached resources',()=>{const scene=new THREE.Scene(),adapter=new ThreeObservationRenderer(scene),base=visualRegistry.defaults();const low=parseHashHex(`${'ab'.repeat(18)}00000000${'cd'.repeat(10)}`),high=parseHashHex(`${'ab'.repeat(18)}ffffffff${'cd'.repeat(10)}`),zero=parseHashHex('00'.repeat(32));const frame:ObservationFrame={tick:0,stateDigest:parseHashHex('11'.repeat(32)),entities:[{hash:low,provenance:{origin:'genesis',createdAtTick:0,seed:'seed1'},createdAtTick:0,contextHash:zero},{hash:high,provenance:{origin:'genesis',createdAtTick:0,seed:'seed2'},createdAtTick:0,contextHash:zero}],bonds:[],clusters:[],condensationRecords:[]};adapter.setVisualConfiguration(base);adapter.update(frame,[]);expect(adapter.debugEntityGeometryCount()).toBe(2);for(let maximum=2;maximum<=5;maximum+=1)adapter.setVisualConfiguration({...base,'entity.maxHashSmoothness':maximum});expect(adapter.debugEntityGeometryCount()).toBeLessThanOrEqual(2);adapter.dispose();expect(scene.children.filter((child)=>child.name.startsWith('observation:'))).toHaveLength(0);});
});
